.github/workflows/python-app.yml
README.md
docs/conf.py
poetry.lock
pyproject.toml
pytest.ini
src/preferences.py
src/utilities.py
tests/conftest.py
tests/test_guiguts.py

Also add to Github Actions
Make Preferences use different JSON file (and delete it) when testing, to avoid testing affecting normal use, and vice versa.

Add testing with `pytest`

---

.github/workflows/python-app.yml
docs/conf.py
src/file.py

Check documentation coverage

---

src/guiguts.py
src/mainwindow.py

User can now adjust proportion of window used for text & image.

Use PanedWindow to hold text and image

---

README.md

A small tweak to the README for how to run GG2 with poetry.

Include how to run GG2 from poetry

---

src/guiguts/application.py
src/guiguts/file.py
src/guiguts/mainwindow.py
src/guiguts/preferences.py

1. Allow user to choose png dir by right-clicking "See Img"
2. Enable Auto Img by double-clicking "See Img"
Fixes #62

Image improvments

---

src/guiguts/file.py

In fact, shows the first page number, even if it's not "1"

Show "page 1" if before all page markers

---

src/guiguts/application.py
src/guiguts/file.py
src/guiguts/mainwindow.py

Add Close to File menu

---

src/guiguts/application.py
src/guiguts/mainwindow.py

Outputs messages with a timestamp to a dialog as well as to stderr. Shows the dialog if currently hidden.
Currently supports errors. Other message types could be added later if needed.

Add message log

---

docs/index.rst
poetry.lock
pyproject.toml
src/guiguts/application.py
src/guiguts/dialogs.py
src/guiguts/file.py
src/guiguts/page_details.py
src/guiguts/preferences_dialog.py

1. Store page label information in project json file
2. Show page label in status bar
3. Left click page label to go to a page using its page number
4. Allow user to configure page labels by right-clicking label in status bar
5. In config dialog, click style (Arabic/Roman/ditto) or number (number/increment/no count) to cycle between values. This is similar but more streamlined than GG1 version of dialog.

Page labels

---

src/guiguts/application.py
src/guiguts/child.py

Superseded by decision to implement tools as python modules.

Remove experimental "spawn process"

---

src/guiguts/file.py
src/guiguts/maintext.py
src/guiguts/search.py

So useful, I wrote it twice! The two methods were identical - replaced get_index with rowcol.
Fixes #154

Merge duplicate get_index/rowcol methods

---

src/guiguts/page_details.py

Shift-clicking cycles the style and number settings in reverse order, making it possible to get the setting you want in one click, which can be helpful if wanting to change several pages.
Tooltip also updated.
Fixes #211

Add Shift-click to reverse in page labels dialog

---

src/guiguts/application.py
src/guiguts/preferences.py
src/guiguts/tools/jeebies.py
src/guiguts/tools/pptxt.py

1. Use paragraph text to find jeebies but report them by their line and
column position in file.
2. Implement a more sophisticated and comprehensive jeebies identification
algorithm.
3. Implement tickbox selection of jeebies check level.
4. Improve efficiency by doing all checks over a single pass of paragraph text.

Report jeebies by line/col position

---

src/guiguts/checkers.py
src/guiguts/tools/jeebies.py

1. Ctrl/Left-click toggles highlighted he/be on file line.
2. Fixed an oversight in checkers.py so that start mark now has left gravity,
and the end mark has right gravity.

Add Ctrl/Click functionality for error correction in Jeebies.

---

src/guiguts/search.py

Replace All did not add the search term to the search history.
Fixes #234

Add search term to history during replace (all)

---

src/guiguts/application.py
src/guiguts/file.py
src/guiguts/maintext.py
src/guiguts/utilities.py
tests/test_guiguts.py

1. Sub menu of `Search` menu to set/goto bookmarks
2. Keyboard shortcuts like GG1: `Cmd/Ctrl+1`, `2`, ...`5` to go to, and `Shift+Cmd/Ctrl+1` to set the bookmark.
3. Brief highlight (like GG1) to show it's been set/found (bell if not)
4. Bookmarks stored in project .json file.

Add bookmarks

---

src/guiguts/application.py
src/guiguts/misc_tools.py

1. Tools->Normalize Selected Characters
2. Works on selected characters
3. Supports column selection
4. Only replaces characters if changes are needed
5. Works one line at a time in case user selects whole file, otherwise page markers would all end up at start.

Add Unicode NFC normalization

---

src/guiguts/maintext.py

Where clipboard is added to by Tcl/Tk, schedule a call to a routine that sets the clipboard to its own contents, but using the `pyperclip` module instead of Tcl/Tk.

Fix cut/copy to BBedit bug

---

src/guiguts/file.py
src/guiguts/maintext.py
src/guiguts/search.py

Without this, page boundaries all end up at the start of the replaced text. This commit repositions any
page boundaries that are internal to the replaced
text at the same proportions through the new text
that they were through the old text.
In fact, this is the general text replace function, which is used internally, not just for Search/Replace.
This tackles the first point in #144

Make Search/Replace respect page boundaries

---

src/guiguts/application.py
src/guiguts/checkers.py
src/guiguts/footnotes.py
src/guiguts/preferences.py

Only currently needed for Footnote Fixup, but
implementation is general, so can be used for future checkers.

Add "Suspects Only" toggle to checker dialogs

---

pyproject.toml
src/guiguts/application.py

First step in making GG2 available to others.
Setting version to `2.0.0-alpha.1` in `pyproject.toml` and querying it in the application gives the string `2.0.0a1` which seems acceptable.

Use semantic versioning & display in title bar

---

src/guiguts/application.py
src/guiguts/maintext.py
src/guiguts/misc_dialogs.py
src/guiguts/preferences.py

Add controls to Prefs dialog to allow user to select the font family and size used in the main text window.
Default is "Courier 10", which is guaranteed by Tk to be available on all platforms.

Add font family & size preferences

---

CHANGELOG.md
pyproject.toml

Add changelog with brief description of alpha.1 features, and changes in alpha.2

Version 2.0.0-alpha.2

---

src/guiguts/maintext.py

Make cursor visible after paste

---

src/guiguts/misc_tools.py

Single quote check needs to ignore things which are "clearly" apostrophes. For now, that means close-quote which has alphabetic character on both sides.
This logic didn't fit into the generic "unmatched" code, so extracted some customized code for single curly quotes.
Fixes #312

Improve single quote "unmatched" check

---

src/guiguts/checkers.py
src/guiguts/mainwindow.py
src/guiguts/widgets.py
src/guiguts/word_frequency.py

1. "Working" label shows in bottom right corner.
2. Cursor changes to "watch" image while busy.
Fixes #299

Implement "busy" notification

---

src/guiguts/tools/pptxt.py

No longer splits words at hyphens and
then adding those parts to the 'words'
dictionary.
Checks only for word differences
such as "motor-car" and "motorcar".

Fix over-sensitivity of PPtxt hyphenation check

---

src/guiguts/maintext.py

Also addresses point 5 of issue #177, i.e. the insert cursor is left in a sensible location after column select.

Highlight line number of the current line

---

README.md

Add notes from inkandamaranth to README

Add Chromebook installation notes

---

src/guiguts/search.py

See issue #373 for detailed description of problem

Ensure search box has focus when SR dialog popped

---

src/guiguts/search.py

Also, trap bad regexps in replace strings

Implement `\C...\E` to execute python code

---

src/guiguts/search.py
src/guiguts/widgets.py

@srjfoo - please see if this fixes #393 
It's not going to be merged as it is - it's just for testing purposes.
I commented out two lines. If they have worked, you could uncomment each in turn and check which is the one that fixes it.
Note, this PR does not have the latest backref regex work in it.

Investigate narrow S/R dialog

---

src/guiguts/application.py
src/guiguts/checkers.py
src/guiguts/maintext.py
src/guiguts/mainwindow.py
src/guiguts/misc_dialogs.py
src/guiguts/preferences.py
src/guiguts/root.py
src/guiguts/search.py
src/guiguts/widgets.py

Non breaking space (by typing two spaces into compose sequence dialog) was accidentally discarded by an
"isprintable" check.
Fixes #406

Compose sequence didn't insert some characters

---

src/guiguts/misc_dialogs.py

1. Block list now contains all current Unicode blocks.
2. Dropdown menu still just contains the GG1 list of blocks (i.e. those that are likely useful for PPing). This list can easily be updated to include/remove blocks (in the code, not by the user).
3. This means all characters found with the Unicode Search dialog should now have a block name next
to them, which can be clicked.
4. Note that (3) above means you can show a block in the Block dialog that isn't in the dropdown. However, that doesn't seem to be a problem.
5. Especially if you do what is described in 4, you may get characters showing in the block dialog that are "new" (i.e post 2002). The tooltip over a "new" character in the Block dialog will have a warning icon, just like its description in the Search dialog.
Fixes #421

Update Unicode block list

---

CHANGELOG.md
pyproject.toml

Updated changelog, and after `poetry install` should display new version number in title bar.

Prepare for 7th alpha release

---

src/guiguts/application.py
src/guiguts/file.py
src/guiguts/maintext.py
src/guiguts/mainwindow.py
src/guiguts/preferences.py
src/guiguts/root.py
src/guiguts/widgets.py

I know this has wrong font, wrong, colors, no line numbers etc. This is just an experiment to see if it would be worth pursuing. Work so far is minimal - probably quite a bit more to get it to look smart and check what the bugs or limitations are, if any.
You can drag the split up & down, but obviously, it also needs an on/off option somewhere.
Splitting vertically would be possible instead, with a little more complication if you want the option of either a horizontal or vertical split.

Try out split screen

---

src/guiguts/application.py
src/guiguts/preferences.py
src/guiguts/search.py

Allow user to toggle just one replace box & buttons or 3 replace boxes & buttons, using checkbox in the S/R dialog.
Dialog resizes to take account of additional buttons.

Implement multi-replace

---

src/guiguts/word_frequency.py

1. Rework algorithm that finds "flash light" suspect for "flash-light".
2. Improve speed of "Ital/Bold/etc" - about 10 times faster.
3. Ignore case now works properly for "Ital/Bold/etc".
4. Sorting for "Ital/Bold/etc" improved: if sorted alphabetically, put the marked up and unmarked versions adjacent in the list.
Fixes #443 
Fixes #444

Word Frequency improvements

---

src/guiguts/application.py
src/guiguts/mainwindow.py
src/guiguts/preferences.py

1. Zoom in & out
2. Fit to image width/height
3. Invert checkbox reverses colors in image
4. Set background of canvas to button background color
5. Use better scaling algorithm to improve image quality
6. Remove lots of complication

Improve image viewer

---

src/guiguts/maintext.py

If BOM appears on first line, remove it.
Fixes the cause of #324

Remove BOM from loaded file

---

src/guiguts/maintext.py

Fixes #469
Also remove logger debug messages and the
potentially unnecessary tracking code

Fix linux traceback from menu bar

---

src/guiguts/checkers.py

Uses max width shown in dialog to determine spacing so that messages align
Fixes #489

Format line.col in checkers to align messages

---

src/guiguts/word_frequency.py

Right aligns frequencies to the width of the largest frequency being displayed

Right align frequency counts in WF dialog

---

src/guiguts/application.py
src/guiguts/file.py
src/guiguts/mainwindow.py
src/guiguts/misc_dialogs.py
src/guiguts/preferences.py
src/guiguts/root.py

Some were previously only accessible through clicking on status bar buttons.
Fixes #474
See #474 for list of changes

Ensure all features are accessible through menus

---

src/guiguts/application.py
src/guiguts/misc_tools.py

Finds single asterisk, double asterisk, etc.
Also finds thought breaks, like `* * *` & similar variations

Add Find Asterisks w/o Slashes

---

src/guiguts/page_details.py

Similar to checker dialogs - provide quick jump to top and bottom using Home/End/Cmd-Up/Cmd-Down
Fixes #514

Bind Home/End to show first/last in page label dlg

---

src/guiguts/application.py

Rearrangement around "Remove Highlights" as discussed in #519

Re-order and re-group Search menu

---

src/guiguts/application.py
src/guiguts/file.py
src/guiguts/maintext.py

1. Don't allow illegal values to be saved
2. Output an error message, rather than using an assertion.
Fixes #546

Improve handling of illegal language codes

---

src/guiguts/maintext.py

Grow line number highlight to full column width

---

src/guiguts/page_details.py

The widget requires both its "selection" and its "focus" to be set to work properly. Allowing some things to work on focus and some on selection made it
possible for the selected page to be out-of-sync
with the displayed page when Cmd+up/down was
used in conjunction with plain up/down.

Fix page label bug with Cmd-up/down

---

src/guiguts/checkers.py
src/guiguts/word_frequency.py

Button copies the list of results to the clipboard. This can be done with Ctrl-A & Ctrl-C, but that's a bit obscure, and at least one person didn't realize.

Add "Copy Results" button to checkers & WF

---

src/guiguts/application.py

Opens manual page in browser
(As requested in [DP forum](https://www.pgdp.net/phpBB3/viewtopic.php?p=1355160#p1355160))

Add Regex Cheat Sheet to Help menu

---

src/guiguts/maintext.py

When select-dragging beyond the widget boundary, releasing the click would result in the selection converting back to linear, and scrolling infinitely until clicking back into the window.
This was caused by the event falling back to the default, due to bind_event() suppressing the original event handler. Change this to an additional binding to allow the normal release behavior to be processed.
This commit also adds a check to stop calling the scroll handler when the boolean is False, moves the boolean being set into the click and release handlers (instead of deeper down where it also affected the shift-click mechanism), and uses the event widget reference instead of relying on focus_widget as it was doing before.
This is a followup to #596 and #620.

Fix select-auto-scroll problem on out-of-bounds release

---

src/guiguts/mainwindow.py

Fix Cmd-0 crash when no image loaded

---

docs/index.rst
src/guiguts/illo_sn_fixup.py
src/guiguts/tools/jeebies.py

Also a couple of minor doc "errors" fixed.

Added recent modules to sphinx index

---

src/guiguts/illo_sn_fixup.py

It now looks forward to find the first "normal" line, i.e. not an empty line, a `[Blank Page]`, another illo/SN, nor a page separator line. Then it finds a normal line, it checks if the line above it is blank, meaning it's the start of a paragraph. If not, then the illo/SN is mid-paragraph.
Fixes #595

Improve detection of mid-para illos/SNs

---

CHANGELOG.md
pyproject.toml

Testing notes: needs a `poetry install`

Update Changelog & Readme for alpha.13

---

src/guiguts/html_convert.py

Fixes #678
NTS: depends on #677, so merge after that

Make HTML Autogeneration show "busy"

---

docs/index.rst
src/guiguts/application.py
src/guiguts/tools/bookloupe.py

This tool is not identical in behavior to the standalone tool used in GG1, but it does do essentially the same tests, and reports them in a similar way.
There will be reports from this that the GG1 tool does not report, and vice versa.
The aim is to provide a useful tool for PPers.
Future work will probably include more on curly quotes, and other features of "recent" DP books.
Fixes #463

Implement bookloupe

---

src/guiguts/application.py
src/guiguts/html_tools.py
src/guiguts/misc_dialogs.py
src/guiguts/preferences.py
src/guiguts/search.py
src/guiguts/word_frequency.py

Very similar to GG1 feature
See [manual](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_2_Manual/HTML_Menu#Auto-Illustrations) for more details on how to use.

Add Auto-Illustrations feature

---

src/guiguts/tools/bookloupe.py

1. Don't report extra period if lowercase character after the period is just some inline markup
2. Don't report  `Footnote 1:` as standalone 1
Fixes #709

Fix a couple of bookloupe nits

---

src/guiguts/checkers.py
src/guiguts/tools/bookloupe.py

1. Add generic feature to checker dialogs
2. Implement it for bookloupe
Fixes #717

Add View Options feature

---

src/guiguts/maintext.py
src/guiguts/search.py

This PR is mostly about improving / fixing the behavior of "highlight all matches" during a search. See #705 where I'll be going next to respond to some of the issues raised.
This PR includes:
- Moved `SearchDialog._find_all` to `MainText.find_all`. This was moved because trying to use it in the former location led to a circular import I couldn't resolve, and the method itself had no particular tie to `SearchDialog` or to search.py
- Improved `MainText.get_screen_window_coordinates` to deal with IndexRange, not a tuple of strings
- Reimplemented "highlight all matches" such that it will redraw the highlights on-demand during the viewport redraw phase, making it more dynamic, but also focusing only where the user can see, to avoid re-highlighting the entire file out of view. This brought a …

Reimplement "highlight all search matches"

---

src/guiguts/tools/bookloupe.py

Improve bookloupe message wording

---

src/guiguts/search.py

1. If Search for a non-matching string
2. If "Find Next" (Cmd+g / F3 / menu) for a non-matching string
3. If "Replace & Search" and there are no more matches, typically when the last replacement has been made.
In all these cases, it used to (and still does) ring the bell, but now shows a "No (more) matches found" message.
Fixes #734

Add "not found" messages to SR dialog

---

src/guiguts/application.py
src/guiguts/tools/pptxt.py

While we're here, move PPtxt to the Text menu.
Fixes #311

Don't report asterisks multiple times in PPtxt

---

src/guiguts/mainwindow.py

Make image controls more compact, compressing into a single row.
Make zoom scaling a little finer (1.1 instead of 1.3).
Adds next / previous image buttons, allowing the user to navigate among images manually without affecting the currently displayed text. Using this navigation automatically turns off "Auto Image". The Image viewer will display any images in the image folder, even if they are not part of the base scanset (i.e., high-res scans, covers, etc., will also be displayed).
Addresses some, but not all, issues raised in #483.

Improvements to Image Viewer controls

---

src/guiguts/application.py
src/guiguts/root.py

Add `Invert Image` to the View menu

---

src/guiguts/mainwindow.py

Image viewer control layout interfered with scrollbar width.

Fix layout issue with image viewer controls

---

src/guiguts/html_tools.py

Add space around `-` at one point in #747 code

Placate flake8

---

CHANGELOG.md
pyproject.toml

I think this is the list for alpha 15.

Fix version & changelog for alpha.15

---

src/guiguts/application.py

Report GG version, python version, Tcl/Tk version, OS platform and release. To aid with support/debugging.

Add version numbers to Help-->About Guiguts

---

src/guiguts/application.py
src/guiguts/html_tools.py
src/guiguts/preferences.py

Use SOAP/XML interface to validator and display
results in a checker dialog.
Allow user to select CSS 2.1 or CSS 3 & store in prefs.

Add CSS Validator to HTML menu

---

src/guiguts/application.py
src/guiguts/mainwindow.py

> Usually, one would expect that sort of thing to take effect dynamically

Reload internal image if hi-contrast pref changed

---

src/guiguts/maintext.py

Clicking and releasing on the line number gutter selects the clicked line. Clicking and dragging in either direction selects the range of lines.
Caveat: due to the implementation of the line gutter, currently dragging beyond the visible range of lines is not supported. It may be possible with further work, but I didn't attempt it.

Select lines by dragging over line-number gutter

---

src/guiguts/application.py
src/guiguts/file.py

Even if AutoImg is on, it should only prompt when a new file is loaded, not when a file is saved.
Fixes #812

Don't prompt for scans folder during Save As

---

src/guiguts/misc_tools.py

Don't report things like `100/length`
Fixes #815

Reduce false positives from unmatched block markup

---

src/guiguts/application.py
src/guiguts/checkers.py
src/guiguts/html_tools.py
src/guiguts/preferences.py

1. User needs to install ebookmaker themselves using the ebookmaker installation instructions.
2. User needs to tell GG where ebookmaker is installed.
3. Can choose which formats to be created (EPUB2 is always created)
4. Epub files are created in the project folder

Add Ebookmaker integration

---

src/guiguts/application.py
src/guiguts/maintext.py

Called automatically on file save, and also available in the Edit menu.

Add delete eol space & eop blank line features

---

docs/index.rst
src/guiguts/application.py
src/guiguts/ascii_tables.py
src/guiguts/maintext.py
src/guiguts/preferences.py

Testing notes: The manual page (https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_2_Manual/Text_Menu#ASCII_Table_Effects) will be useful. It's copied directly from GG1 because it has helpful screen shots of example tables. I'm not concerned with minor manual edits that are needed to remove GG1-specific things at this point.

Implement ASCII Table Effects

---

src/guiguts/application.py
src/guiguts/misc_dialogs.py
src/guiguts/preferences.py
src/guiguts/widgets.py

Added to Advanced tab in Prefs dialog.

Add pref for whether tooltips are displayed

---

src/guiguts/search.py

Previously, if Count, Find All or Replace All were done on a column selection, only the first line of the
column selection would be used for the count, find or replace.
Now, the whole column selection is used.
Fixes #140

Make S/R respect column selections

---

src/guiguts/html_tools.py

Using GET required the whole of the CSS block to be sent via a param, causing large blocks to hit a size limit.
Using POST, any size file works fine, and it's also OK to send the whole file instead of extracting the CSS block and then offsetting the line numbers reported in error messages.
Tried switching to json response instead of SOAP, but the json response errors omit some useful context, so kept with SOAP.
Fixes #877

Use POST instead of GET with CSS validator

---

src/guiguts/footnotes.py

Later matches didn't replace correctly when there was more than one FN anchor on a line.
Fixes #881

Reindex fine tuning

---

src/guiguts/word_frequency.py

Underscore is no longer treated as a word character, which it was, inconsistently.
Also, remove `001.png` & similar from word list, mostly for ppgen users.
Fixes #887

Fix WF bug when underscore follows `7NaAlSiO`

---

src/guiguts/application.py
src/guiguts/maintext.py
src/guiguts/mainwindow.py
src/guiguts/misc_dialogs.py
src/guiguts/preferences.py
src/guiguts/root.py
src/guiguts/widgets.py

1. All Prefs dialog toggles added
2. Image viewer Auto-fit toggles added
3. Change theme buttons added
4. "Toggle" before label in command palette list changed to "(toggle)" after label to avoid having lots of commands beginning with Toggle alphabetically, and assist with user-filtering of commands.

Add more shadow commands

---

CHANGELOG.md
pyproject.toml
src/guiguts/spell.py

Cmd/Ctrl-clicking a message removed 2 messages.

Fix spell check double removal bug

---

src/guiguts/misc_dialogs.py

Restore "High Contrast" pref label

---

src/guiguts/misc_tools.py

Check if previous page ends in "]" or "]*", and if so, don't attempt a "join page" operation, because it won't cope. PPer has to deal with it manually.
Fixes #924

Don't join page seps if EOP foot/sidenote/illo

---

src/guiguts/application.py
src/guiguts/html_tools.py

Uses in-development API - not to be merged like this.

Add ebookmaker using API

---

src/guiguts/misc_dialogs.py

Oops - small bug broke the Run button

Fix Run button in Command Palette

---

src/guiguts/mainwindow.py

Scroll Image Up, down, left & right. User can define their own shortcuts.
Fixes #483 (the only bit left to do)

Add shadow commands for image scrolling

---

src/guiguts/application.py
src/guiguts/ascii_tables.py
src/guiguts/checkers.py
src/guiguts/footnotes.py
src/guiguts/html_convert.py
src/guiguts/html_tools.py
src/guiguts/maintext.py
src/guiguts/mainwindow.py
src/guiguts/misc_dialogs.py
src/guiguts/misc_tools.py
src/guiguts/search.py
src/guiguts/tools/jeebies.py
src/guiguts/tools/levenshtein.py
src/guiguts/tools/pphtml.py
src/guiguts/widgets.py
src/guiguts/word_frequency.py

To support those who prefer to use the keyboard

Allow tabbing to all buttons and checkboxes

---

src/guiguts/tools/pphtml.py

Accept charset definition in non-HTML5 file.
Fixes #1023

Improve charset check in PPhtml

---

src/guiguts/application.py
src/guiguts/mainwindow.py
src/guiguts/widgets.py

Previous fix didn't stop it happening again 😊
This time fix by inheriting from ttk.Style, and overriding the buggy method.

Fix Tk9 theme query bug more robustly

---

src/guiguts/misc_dialogs.py

Add `[**` to surround auto-match list

---

src/guiguts/word_frequency.py

1. If no more occurrences of word, reset current insert position to start/end of file (depending on direction) similar to GG1, as well as ringing the bell.
2. Allow Shift-click on word to search backward from current location - finds last occurrence on first click
3. Fix bug where Home/End/Cmd+Up/Down keys didn't show the first occurrence of a word if that word was already highlighted, for example, if pressing Home twice, the second press went to the second occurrence of the word, instead of always the first one.
Fixes #926. As noted in the issue description, point 2 in the issue was already done by GG2.

Improve WF navigation

---

src/guiguts/maintext.py
src/guiguts/search.py

This is a suggested solution for the "Highlight Char, String & Regex" GG1 feature.
Use the S/R dialog to set Regex, wholeword, case
sensitivity, and optionally "In Selection". Then use Highlight All to highlight all matches. The settings, such as wholeword are "frozen" for the highlighting, i.e. if the user then changes the settings or the search string, it doesn't change the highlighting.
Like GG1, the color is the same as the quotes
highlighting. Remove highlighting by using the
Search->Remove Highlights button.
New button has a shadow command, like the other
S/R buttons.
Fixes #927

Add Highlight All to S/R dialog

---

src/guiguts/ascii_tables.py

1. If whole of first column consists of spaces, ignore the "Rewrap" setting, it doesn't wrap to zero width
2. When Inserting a Vertical Column, keep the cursor in the column it was previously in, i.e. add the column to the RIGHT of the cursor.
Fixes #1042
Fixes #1046

Fix minor ASCII Table bugs

---

src/guiguts/html_tools.py

When running ebookmaker locally or via the API, things fail badly if it is not told to build at least one format. Previously, GG forced the user to build EPUB2, but with this commit, they can choose which formats to build and receive a polite error message if they don't choose any formats.

Let user decide whether to build epub2 file

---

src/guiguts/search.py

`\C` already executes python code. This commit adds `\U \L \T \A \R` similar to GG1 to convert to uppercase, lowercase, titlecase, anchor_name (removes accents/symbols), Roman, respectively. 
All such commands are terminated with `\E` and cannot be nested.
Fixes #997 
Testing notes:
Search: `(....)`
Replace: `\U\1\E`
Search: `(\d\d)`
Replace: `\R\1\E`

Add extended regex commands

---

src/guiguts/word_frequency.py

Minor WF label changes

---

src/guiguts/application.py
src/guiguts/misc_tools.py

1. Add View Options
2. Make error type use the error prefix (default red text)
3. Small code re-org to bring into line with more recent checkers
Fixes #1082

Add View Options to Basic Fixup

---

src/guiguts/checkers.py

Fixes #1145
Bookloupe, Curly Quote Check and Basic Fixup have View Options dialogs.

Make View Options columns more level

---

src/guiguts/word_frequency.py

If the word began or ended with an emdash, and the occurrences in the file had a non-word character before/after, then WF didn't navigate to them. Example in linked issue.
Fixes #1195

Fix WF search for emdash words

---

src/guiguts/checkers.py
src/guiguts/word_frequency.py

Exception could be triggered if dialog was closed while tool was still running.

Trap exception if WF or Checker closed early

---

src/guiguts/application.py

Add shadow commands for Recent File 1, 2 & 3

---

src/guiguts/spell.py

The following now all do the same, which is to add to the project dict and remove all occurrences from list:
1. Click Add to Project Dict
2. Cmd/Ctrl-P (GG1 shortcut)
3. Cmd/Ctrl-left click
4. Cmd/Ctrl-right click
Button shortcut is unchanged "Cmd/Ctrl-P or Ctrl-click message", which is now both correct and useful.
The following now all do the same, which is to add to the global dict and remove all occurrences from list:
1. Click Add to Global Dict
2. Cmd/Ctrl-A (GG1 shortcut)
3. Shift-Cmd/Ctrl-left click
4. Shift-Cmd/Ctrl-right click
Button shortcut is now "Cmd/Ctrl-A or Shift Ctrl-click message".

Improve Add to Project Dict in Spell Check

---

src/guiguts/application.py
src/guiguts/content_providing.py

Works the same as GG1, apart from minor difference in the exact format of the page separator lines.
Fixes #1147

Add TIA Abbyy OCR import

---

src/guiguts/misc_dialogs.py

Use tk (not ttk) to set font for label buttons.

Display unicode block characters in correct font

---

CHANGELOG.md
pyproject.toml

Prepare for final release 2.0.0

---

src/guiguts/search.py

When using the Replace All buttons in the S/R dialog, if the button is Shift-clicked, it only replaces the strings that exactly match the current match. It then moves on to the next match.
"Exactly" means not regex (regardless of dialog setting) because it's an exact match; case sensitive (regardless of dialog setting) - could be argued it should match dialog; whole word matches dialog setting (or chaos would ensue)
Fixes #609

Implement "replace identicals" feature

---

src/guiguts/misc_dialogs.py

1. Ensure focus is in the dropdown when dialog is created
2. If user types, store the characters they type
3. If they pause between characters, reset and start again
4. If they type a string that matches the start of a word in the Unicode block name, jump to it. For example, typing `math` can match `Mathematical Operators` or
`Miscellaneous Mathematical Symbols`
5. If they type a string that is the start of a 4-digit hex unicode codepoint, go to the block that contains that codepoint, if it is in the list. For example, if they know that open single quote is `U+2018`, they can type `201` or `2018` and it will find the `General Punctuation` block which has range 2000-206f.
Fixes #944

Add "type-to-search" to Unicode Block dialog

---

src/guiguts/maintext.py

"Highlight Surrounding Quotes & Brackets" now ignores quotes that are surrounded by letters, e.g. `didn't`. Should work for straight and curly quotes.
Fixes #1239
Testing notes: [Test file](https://github.com/user-attachments/files/21150946/herzen.zip) from linked issue can be used. Specific location in file is suggested in the issue. Also try the same but after replacing straight quotes with curly.
Note this also fixes a bug in `master` introduced by #1315 - if you have highlighting turned on, then as you move around, the highlighting should update to highlight the surrounding quotes or brackets. But if you click to a new location on screen, rather than using arrow keys, it doesn't update in `master`. It should with this commit.

Skip quote surrounded by letters when highlighting

---

src/guiguts/illo_sn_fixup.py

Fix bug with illo wrongly marked as mid-para

---

src/guiguts/application.py
src/guiguts/content_providing.py

Add dialog to give flexibility over prefix, start, end & suffixes for each section of the file.
Fixes #1407

Improve renumbering

---

src/guiguts/word_frequency.py

In `master` an accented word was only suspect if
it also appeared in non-accented form, e.g.
"révolution" and "revolution". The case of
"révolution" and "rèvolution was not flagged.
Now any variation on accenting is flagged.
Also, if all 3 versions:
"revolution", "révolution" and "rèvolution"
occurred, the non-accented form was inserted
twice into the list. Now fixed.
Fixes #1360

Improve WF diacritics check

---

src/guiguts/application.py
src/guiguts/checkers.py
src/guiguts/content_providing.py
src/guiguts/maintext.py

1. Change order of Char Suite options
2. Clarify wording on WF Char Count toggle for highlighting chars not in selected char suites
3. Use green for Keep prefix, red for Remove prefix
4. Add extra error prefix color to Settings dialog so it can be configured
Fixes #1449

Further CP improvements

---

src/guiguts/utilities.py

Fixes bug that `Dus` & `Düs` are not reported as suspects by WF diacritics check

Don't treat umlaut-ed characters as adding an "e"

---

src/guiguts/footnotes.py

Added Busy.busy() calls to the reindex and the major move functions.

footnotes.py - add Busy.busy() calls to reindex and major moves.
