gg_menubar.py, gg_prefs.py, gg_prefsdialog.py, gg_tkutils.py, guiguts.py
Only current preference used in program is whether image dialog is "Docked" or "Floated" - key is "ImageWindow"
Prefs are stored in the normal Guiguts GGprefs directory (`HomeDir/Documents/GGprefs` on Windows/Mac, or
`HomeDir/.GGprefs` on Linux). Filename is `GGprefs.json`
Could manually add another "preference" by editing `GGprefs.json` but of course program will do nothing with it, apart from loading it and saving it again. E.g. add line to `GGprefs.json`, `  "Favorite Color": "red"`
The docked/floated status of the image window should now be persistent across runs of the program. Prefs are loaded when program starts - anything not set in the prefs file will default to a value set in the program ("ImageWindow" defaults to "Docked")
To test dialogs, use Edit->Preferences to edit all the …
=> Add preferences and dialog to edit them

child.py, gg_menubar.py, guiguts.py
In File menu, Spawn Process runs `child.py` as a subprocess, and sends it some text as input.
This script accepts the standard input, echoes what it receives, then uppercases it and echoes that. It also outputs a message to stderr.
=> Add option to test spawning a tool

docs/index.rst, src/file.py, src/guiguts.py, src/mainwindow.py, src/preferences_dialog.py
1. Separate out File operations into their own module
2. Also fix key binding bug - by default Ctrl-O adds a blank line to a Text widget. We have bound it to Open File in our Text widget, but the class binding was still being called, so doing Open File also added a blank line (at the end of the file) so the file appeared "edited" immediately after loading. By returning the string "break" from the instance callback, it stops the class callback being called.
=> Separate out File operations

src/file.py, src/guiguts.py, src/mainwindow.py
Assume pngs are in `pngs` subfolder below text file location.
Also, minor bug fix: set cursor to start of file when loaded - will be overridden by "current" location when last saved if there is a bin file.
=> Make png load work better

src/mainwindow.py, src/preferences_dialog.py
Things like buttons have a more native file when the `ttk` version is used.
May turn out to be a pain to configure, but may be OK.
=> Use ttk in place of tk where possible

README.md
This adds dev instructions for macOS and some slight restructuring to accommodate two platforms plus some common bits.
I'm guessing at the `poetry use` incantation for Windows -- it should point to the python binary. Without this poetry will use the first version of python on the path. For Windows this might not be a problem, but for macOS it is as macOS comes with a version and multiple can be installed concurrently from Homebrew. To keep the instructions parallel I added the Windows example but we can leave that out if it's too confusing.
=> Add macOS dev instructions

src/file.py, src/guiguts.py, src/mainwindow.py
Status bar labels changed to buttons, to give more modern look, and because buttons change appearance when mouse hovers over them, rather than coding it, and because they are buttons!
Improved `get_current_image_name` to cope with cursor being coincident with one or more page marks. Since typically they are at the start of a line (at least initially) it can be confusing to place the cursor at the start of a line and the page number being reported as the previous page.
=> Add "goto" and "see img" buttons

src/file.py, src/guiguts.py, src/mainwindow.py, src/preferences.py
1. Override callback when Tkinter exception occurs. Later, instead of printing & showing message dialog, this can be output to message log along with other errors.
2. Add warning bell (visible/audible) controlled by a pref. One way to get bell is to use the `<` (Previous image button) to try to go back before the start of the file.
3. Make (temporary) Prefs dialog show default prefs settings, not just those that the user has set.
=> Add warning bell & catch Tkinter exceptions

src/guiguts.py, src/mainwindow.py, src/preferences.py, src/preferences_dialog.py, tests/test_guiguts.py
To simplify use of preferences, allow
`preferences["key"] = "values"`, instead of requiring call to `set` method.
=> Provide get/setitem methods for preferences

README.md
The install directory for Homebrew varies on Intel and Apple Silicon systems. This command works for either.
Technically, it's possible to install Homebrew in any path. So this approach would also find Homebrew if installed in a custom path that is not the normal platform default.
=> Use dynamic homebrew path

LICENSE.txt, README.md, src/guiguts/application.py
Include GPLv2 `LICENSE.txt`
Add Copyright and short notices to `README.md` and to the Help->About dialog.
=> Add GPLv2 licensing

src/guiguts/file.py
Page markers from old file were left behind - if there were fewer pages in the new file, this caused the page forward/backward code and image viewer to fail.
Fixes #63
=> Reset page markers when loading file

src/guiguts/preferences.py
Accessed dictionary directly instead of via `__getitem__` meaning it didn't fall back to the default if the user had not set the preference.
=> Fix to AutoImg key bug

src/guiguts/file.py
The `bin" file will contain project specific settings, such as page break locations, current editing location in file, image directory, etc.
It already used JSON, but previously retained the `.bin` suffix from GG1. This causes confusion, so better to give it a `.json` suffix.
Still referring to it as the "bin" file in comments, etc.
=> Use `.json` suffix for "bin" file

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py
This feature requires that the FIle menu can be recreated, whenever you change the "recent documents" list.
The reason for 9 recent documents is for the menu keyboard navigation (1 to 9) though we could make 0 do a tenth if anyone objects. Seems like 9 is enough though.
=> Remember & offer `Recent Documents` in File menu

src/guiguts/application.py
The `Ctrl+D` and `Ctrl+F` shortcuts were just a temporary experiment, and clash with other desirable shortcuts.
=> Remove Ctrl+D & Ctrl+F shortcuts

docs/index.rst, src/guiguts/application.py
Renaming of guiguts module to application stopped the coverage checks from working.
Fixing it showed a couple routines that needed docstring.
=> Fix sphinx coverage check

src/guiguts/application.py
In Mac applications, the standard location for the "Quit" menu item is under the so-called "Application" menu. Tkinter automatically supplies this by default. The second Quit item in the file menu is redundant.
The default Quit menu item binds Cmd-Q, so the menu item removed by this commit was not actually able to bind Cmd-Q, though it clearly attempted to do so.
I tested both of the Quit menu items. Both behaved in the same way, asking if the user wished to save their changes before exit (if the file state was dirty). As far as I can tell, this removal doesn't create any behavioral change.
=> (Mac) Remove redundant "Quit" item from File menu

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py
Previous test was wrong: instead of checking if the scan file exists, it makes sense to check if a scan dir has been chosen.
Now avoids loop, and doesn't turn off Auto Img just because you haven't set up the scan dir.
Fixes #70
=> Avoid Auto Img dir selection loop

src/guiguts/application.py
Closing the window via the Window Manager needs to check if the file should be saved first. 
User can respond: 
Yes - file is saved, or "save as"dialog appears if file hasn't been saved previously - cancelling this save returns to the app. 
No - app exits.
Cancel - returns to app.
=> Check for save when app closed via WM

.github/workflows/python-app.yml, README.md, poetry.lock, pyproject.toml
As per discussion in #57, this is a compromise between using 3.12 and not causing undue hassle for Linux users.
Also, while here, update black version to 23.12, which is the last release using the 2023 stable style.
Also update installation documentation to cover python versions.
Fixes #57
=> Upgrade python version to 3.11

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py, src/guiguts/preferences_dialog.py, tests/test_guiguts.py
Preferences were being saved every time AutoImg was checking for whether to load an image, because the "docked/floated" flag was set.  Altered so that the prefs are only saved when the value is changed, not if it is set to the same value as it formerly was.
When getting a preference that was a list (like the list of recent files, the code was not doing a `copy` (due to my Python ignorance). This meant that when the new recent file was added, it was inserted directly into the prefs list rather than "setting" the list, hence saving wasn't being triggered. Fixed by using `deepcopy` - in fact, a shallow `copy` would be OK for the current settings stored in prefs, but hopefully a deep copy will avoid similar headaches in the future. Performance is not an issue for the relatively small number …
=> Fix bugs in prefs/recent files

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py
1. Add `-d` or `--debug` command line option which starts GG in debug mode: messages will contain `filename:linenum`. Also, debug messages will be displayed (see below).
2. Add basic message handler when program starts that just outputs to stderr.
3. Once GUI is initialized, add two more handlers: one to show error messages in a popup messagebox dialog; the other to log all messages in the message log window, which can be viewed at any time via the `View` menu.
4. In debug mode, all messages are written to stderr and the message log. In non-debug mode, debug messages are not displayed at all, and info messages are only written to the message log, not to stderr.
5. Messages show timestamp, severity of message, and the message. Also filename:linenum when in debug mode.
Fixes #94
=> Use `logging` module for messages

src/guiguts/mainwindow.py, src/guiguts/preferences.py
Get/set via `preferences[key]` versus `preferences.get(key)`
=> Tidy up minor merging issue

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/preferences.py, src/guiguts/utilities.py
Instead of an unhandled exception being reported, log an error if a JSON file cannot be decoded, e.g. if the user has edited it.
Code commonized and used in two places: loading `GGprefs.json` and loading the project json file (the file formerly known as "bin").
It also became apparent that `GGprefs.json` was being loaded too early (when the preferences module was imported into `application.py`, rather than being deliberately initialized at the correct time.)
Order is now: parse args, start logger, load prefs, initialize GUI. This means the logger is initialized correctly in debug mode (set via command line), and provides future opportunity for command line args to suppress loading prefs, which was useful for testing purposes in GG1.
Fixes #71
=> Trap JSON decode errors more cleanly

src/guiguts/file.py
Save As did not update the recent files list, only Load did.
Fixes #103
=> Fix Save As recent files bug

src/guiguts/file.py, src/guiguts/mainwindow.py
User might have edited main file in an editor other than GG. This might mean page boundary positions stored in the bin file no longer match the positions in the text file. By storing an MD5 checksum in the bin file, check that the bin file and text file match, and warn if not.
=> Add checksum to bin file to trap mismatches

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py
1. Add classes to handle Tk Text indexes. GG1 has many occurrences of combining a row/column to get a string Tk Text index, or split an index into the row & column. To reduce this, store in a class which can be constructed with either form, and from which either form can be extracted. Also add a class to handle a single range of such indexes, i.e. a start and end.
2. Add Columnize Selection, which takes the current selection and replaces it with multiple selections in order to form a block from the top-left to the bottom-right of the current selection. This feature may not be required in practice, but is required internally to do Column Cut/Copy/Paste, so I plan to leave it in the menu for now.
3. Make Shift+Mouse-click & drag do column selection. Press Shift, then mouse-click, then drag. …
=> Add column (block) Cut, Copy & Paste

src/guiguts/application.py
On the Mac platform, tkinter is automatically adding a Settings menu under the {application_name} menu, making the "Preferences..." item under the Edit menu redundant.
The customary and "correct" place for the Settings menu item on Mac is the one which is provided by the framework as a default. This PR omits the second menu item on the Mac platform only.
Fixes #115
=> Omit Edit->Preferences menu item on Mac platform

src/guiguts/application.py
The code removed here does not have the intended effect. However, the effect it was aiming for is already included by default, so removing it is a wash.
Fixes #116
=> Remove non-functional "apple menu" code

src/guiguts/mainwindow.py
Bad logic test in smart cut/copy/paste functions meant it sometimes wrongly did column paste instead of default paste.
Fixes #113
=> Fix copy/paste bug related to column select

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py, tests/test_guiguts.py
Primary problem is to do with case on the Mac. Having `Ctrl+Shift+S` and `Ctrl+Shift+s` appeared to stop them from working, whereas that is useful on other platforms due to behavior when Caps Lock is on. More details in code comments.
Couple of minor fixes:
When called via shortcut, functions
get called with an event arg, but not when called via menu. Such functions therefore need optional arg.
Also, after `Cmd+o` and `Cmd+Shift+s` which pop file selection dialogs, on macOS focus was not returned to the main window, which can confuse users.
Fixes #64
=> Fix macOS shortcut key bindings

src/guiguts/mainwindow.py
The `_proxy` method caused problems with overriding methods, as well as catching tkinter exceptions.
Instead, bind relevant events, and override a handful of methods to update the line numbers.
Also, only update linenumbers once each time process becomes idle, even if several events or methods need them updating.
=> Update line numbers without `_proxy`

src/guiguts/application.py
Trying to load the 3 most recent file when there are only 2 files in the list in the prefs file, or similar attempts caused traceback.
Fixes #127
=> Trap attempt to load beyond list of recent files

src/guiguts/maintext.py, src/guiguts/mainwindow.py
1. Cmd with up/down arrow goes to beginning/end of file
2. Shift+Cmd+Up/Down selects to beginning/end of file
3. New `bind_event` method to avoid having many routines needing to return "break" if they are bound to events
4. By default on Windows word characters were any non-whitespace characters, and on Unix alphanumerics and underscores were word characters. Changed on both platforms to be alphanumerics plus apostrophes (straight & curly).
=> Add Mac shortcuts for beginning/end of file

src/guiguts/checkers.py, src/guiguts/search.py
1. Optionally underline a word/words of interest in the results in the checker dialog.
2. When user clicks a result and jumps to relevant place in text, select the relevant piece of text.
3. Remember where selected text is located in the text file, even if user has edited the file since doing "Find All", so that the original line and column numbers are no longer correct ("I remember where the spots formerly was" - Big Jule, Guys & Dolls)
=> Improve features in Checker dialog

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/widgets.py
Currently implemented for the main (root) window and for dialogs inheriting from ToplevelDialog.
Width & Height and position on screen are stored in the GGprefs file. If a dialog is set not to be resizable, then the width and height are ignored when loaded from the GGprefs file, and the dialog is created at its default size. Currently there are no non-resizable Toplevel dialogs.
=> Store geometry of root and toplevel dialogs

src/guiguts/maintext.py
Instead of routines that use `selected_ranges()` needing to
correct for short lines, put the correction directly into
`selected_ranges`.
=> Move special case code to common routine

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py, tests/test_guiguts.py
1. Lang button added to status bar
2. User can click button and enter one or more languages,
e.g. "en" or "en+la" or "fr,de" or "en es cz"
3. Languages are stored in the projects bin file.
4. If a file doesn't have a bin file (and when GG first starts) the
language defaults to the most recently used language, which
is stored in the Prefs file.
Also make Title Case Selection language-dependent:
List of exception words (such as "a" and "the") should only be
used in English texts.
Also resolved two duplicate keyboard navigation letters in the
Edit menu.
=> Add ability to set language(s) for a book

src/guiguts/maintext.py, src/guiguts/utilities.py
1. Stop selection "flipping" when the mouse passes over a short line.
2. Don't highlight whole line when column select includes blank line.
3. Delete & backspace now delete a column selection correctly (like cut, but doesn't add to clipboard).
FIxes #150
=> Fix bugs in column select

src/guiguts/checkers.py, src/guiguts/search.py, src/guiguts/widgets.py
Improve `CheckerDialog.add_entry` method
1. Swap argument order and make the range indicating the area of interest in the main text an optional argument. This makes it possible to add general text to the dialog, e.g. header line.
2. If a range is given, automatically add the start of the range as a prefix to the line of text. Otherwise this code would probably be duplicated in every tool that wants to add lines to the dialog.
3. Stop using "reserved" word `range` as a variable name. 
5. Update Search dialog to use the new checker features, in particular a header and footer to the Search All results.
Add default header widgets to CheckerDialogs
1. Add label showing number of "errors"
2. Add "Re-run" button to re-run the same check
3. Use this for Search Dialog's Find All button.
=> Enhance Checker Dialog

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py
Allow user to add "Page Marker Flags" (e.g. `[Pg001]`) before they save a file and edit it in a different editor. When file is loaded back into GG2, location of Page Marker Flags is used to update the page break locations that were loaded from the bin (.json) file.
Since the bin file and main text file will not match, soften the consequent error message to a warning if the above situation is detected.
The "modified" flag on the file is set if any page boundary locations are updated, because although the text file is not modified, it needs resaving to save the updated bin file.
=> Facilitate use of external editor

src/guiguts/checkers.py, src/guiguts/mainwindow.py, src/guiguts/search.py, src/guiguts/spell.py
1. Change underline to colored text in the dialog for highlighting the word(s) of interest
2. Highlight the chosen line in gray so user knows which one they clicked on
3. Add right-click to remove error from listing - can also remove other lines in the dialog (e.g. the header lines) because some (future) tools have headers partway through their output and a user  may want to get rid of the header when they have handled all the errors in that section.
4. Add Ctrl+left-click (Cmd+left-click on Macs) to "process" the clicked error if possible - see below
5. Add Ctrl+right-click to "process" then remove the error.
Some tools, like jeebies give errors where the correction that needs making is obvious, so if the user "processes" that error, it can make the correction for them, swapping he/be. …
=> Enhance the checker dialog features

README.md
While trying to install on Linux, I found things were missing and GG wouldn't launch. I tested this until the directions as-written worked from a base Ubuntu 22.04 LTS system.
=> README updates for Linux

src/guiguts/application.py, src/guiguts/maintext.py
Previously we were using `range` as a variable name or an argument in some places. `range()` is a global function. This didn't cause any problems with the Guiguts logic, but it did trip up linters and is not best practice.
Fixes #137
=> Refactor: remove `range` as a variable name

.github/workflows/python-app.yml, README.md, poetry.lock, pyproject.toml
Because pylint is currently reporting a bunch of warnings, suggestions, etc, this is in advisory mode only. No matter what pylint finds, the Action will not fail due to pylint.
The way I envision this going is:
- pylint runs in the Action
- Any of us can review its output by looking in the Action tab on Github
- Some things we'll fix, some we'll tell pylint to ignore
- Eventually the output will be empty; then we can choose to remove `continue-on-error` from the Action
The new section in `pyproject.toml` is mostly defaults. The only non-default is that I added `line-too-long` to the `disable` list. Since we use Black for formatting, I don't see value in that one. There are probably other formatting-related warnings we can ignore.
**Suggestion:** Actions are currently running only on …
=> Add pylint to Github Actions pipeline

.github/workflows/python-app.yml
Previously only ran the CI jobs on push to `master`, on pull_request to `master`.
This commit changes to run on push or pull_request regardless of the target branch. Also adds `workflow_dispatch` which allows project owners to launch the CI jobs from the web UI.
(Testing pro tip: the button to run in the web UI will appear only after this change is merged to master.)
https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
=> Run GitHub Actions for more events

docs/index.rst, src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py, src/guiguts/project_dict.py, src/guiguts/root.py, src/guiguts/spell.py, src/guiguts/utilities.py
1. Project dictionary is a JSON file with two lists (good & bad words).
2. Project dictionary is loaded when file loaded
3. File->Project->Add Good/Bad Words to Project dictionary menu entry does what it says, i.e. it looks for good_words.txt and bad_words.txt, adds them to the project dictionary and re-saves it.
4. Ctrl-clicking (Cmd-click on Mac) on spelling error reported by the Spell Checker to add it as a good word to the project dictionary. 
5. Ctrl-right-clicking (or Cmd-Ctrl-click on Mac) adds the spelling and removes that spelling error message from the list of messages
6. Shift-Ctrl-right-clicking (or Shift-Cmd-Ctrl-click on Mac) adds the spelling and removes all error messages about that spelling.
7. Can also select the spelling error message and click "Add to Project Dict" …
=> Add Project Dictionary support

src/guiguts/checkers.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/widgets.py
Fix #159 - several checker dialog issues
1. Stop confusion between different checker dialogs if a new one is popped before the old is closed, e.g. Spell Check and S&R FInd All dialogs. Checker dialogs are used for a variety of tools, and vary in their appearance and controls. They therefore need destroying and recreating, not just deiconifying, if they already exist. This could be solved by inheriting different dialogs from CheckerDialog, e.g. SpellCheckDialog, FindAllDialog, etc. However, it would still be necessary to deal with things like the language changing or the project dictionary changing while a dialog exists, in which case some functions in the dialog would not work correctly. This seems the best fix for now, with very little cost. Other dialogs that inherit from …
=> Checker dialog fixes

src/guiguts/page_details.py
Check for certain keys in `row` dict and bail out if they are not found. Avoids throwing a `KeyError` exception.
Fixes #168
=> Fix exception in Configure Page Labels dialog

.github/workflows/python-app.yml, README.md, docs/conf.py, docs/index.rst, pyproject.toml, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/page_details.py, src/guiguts/preferences.py, src/guiguts/project_dict.py, src/guiguts/root.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/pptxt.py, src/guiguts/utilities.py, src/guiguts/widgets.py, tests/conftest.py
1. Disabled some messages completely, mostly "too-many..." code-style messages, but also "global-statement" warnings - see below for discussion.
2. Retained "too-many-boolean-expressions" as I thought it was a good thing to avoid, and also not likely to happen often, so ok to disable on a per-line basis.
3. Several warnings about improved way to access dictionaries, e.g. using `.items()` acted on.
4. More `*args` arguments removed.
5. Enforced encoding when opening files - good to find, since .json file wasn't being written with utf-8 encoding, so failed to read with utf-8 encoding, depending on contents.
For discussion and advice, please:
- Is disabling the "global-statement" warnings ok with you. We use globals in a few places, and IMO, our code review process should be sufficient to …
=> More lint fixes

src/guiguts/checkers.py
Although we're targeting 3.11 ATM, some devs may have 3.12 and these messages are annoying. Also future-proofs us.
=> Fix flake8 errors reported with python 3.12

src/guiguts/checkers.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/widgets.py
1. Make "destroy" True by default for checker dialogs - it is False by default for other Toplevel dialogs. The pptxt work was merged without the correct setting for "destroy", which is what prompted this edit. The bug which this fixes is that if spellcheck is run, and then pptxt, then pptxt re-uses the spellcheck dialog, with the consequence that clicking "re-run" re-runs spellcheck instead of pptxt.
2. Make FindAll independent of the other checker dialogs, so that it can be displayed at the same time. It is a more general tool, rather than a "checker", so deserves it's own life, otherwise you can't do Spellcheck, followed by Find All occurrences of word.
=> Further small checker dialog fixes

src/guiguts/application.py
The current character's hex ordinal, and unicode name are displayed in a new status bar button.
In future, we may want to re-order the status bar buttons, to put this last because it changes width by quite large amounts for different characters. Alternatively, we may decide to make it a fixed width, or a minimum width that will cover most characters. Or, we may decide to put some buttons, like language on the right hand side of the status bar, so they are not affected by the length of this button.
I'm putting that decision off till later.
=> Add ordinal & unicode char name to status bar

src/guiguts/application.py
Help -> Guiguts Manual now links to a placeholder for the top level of the GG2 manual, rather than the GG1 manual.
No real point in beginning work on the manual yet since things are still too fluid for screenshots and detailed text.
=> Update manual page link

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/utilities.py
1. Put "ordinal" at the end so its length-changes don't make everything else jump around.
2. Add "current selection" label to status bar
3. Show range, e.g. "12.5-13.8", for regular selection.
4. Show rows/cols, e.g. "R:3 C:6", for column selection.
5. Click on label to revert to previous selection.
Due to the issue of drag selection consisting of several selections of increasing length, and we don't want these to fill the previous selection slot, we only store previous selection if both the start and end of the selection are different to the previous ones. This will work in almost every real-life circumstance, and I can't find a reasonable way to avoid it. I investigated whether it was possible to detect if the mouse button was pressed (not easily without interfering with existing …
=> Status bar improvements

src/guiguts/checkers.py, src/guiguts/widgets.py
If entry in checker dialog is selected, then ensure main window is deiconified (but not force-focused)
Because "deiconify" does not work on (some) X-based systems, and may not be needed on macOS, make the iconify/deiconify hack when the program starts, specific to Windows.
Also, when clicking on a checker dialog message, macOS users would expect focus to remain on the checker dialog, but other users would find it helpful to focus on the main window, so make that OS-specific too.
Fixes [#180](https://github.com/DistributedProofreaders/guiguts-py/issues/180)
=> Icon focus

docs/index.rst, pyproject.toml, src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py, src/guiguts/search.py, src/guiguts/utilities.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
1. Implement all WF display types as per GG1, except for "Check Spelling" (use normal spell check), "Unicode > FF" (no longer needed - chars shown in Character Count), "Stealtho Check" (use normal Stealtho feature - NYI), "Check , Upper" & "Check . lower" (they aren't WF checks, just normal checks - NYI)
2. Left click to go to word: first time clicking a word will go to the first occurrence in the file; subsequent clicks will go to the next occurrence, etc. Clicking on a new word resets to starting from the beginning of the file again (similar to GG1 behavior, though there it requires double-click).
3. Right click to pop Search dialog with the word already entered.
4. Also, increase pylint's idea of how much code needs to be similar before reporting it as duplicate from 4 lines to 6. The …
=> Word frequency dialog

src/guiguts/checkers.py, src/guiguts/file.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
If any dialogs are popped, close them when user loads a new text file, or closes the current one.
This work revealed that the marks that are created in the main text window by checker dialogs like find all, etc., were being left behind. If there were several thousand of these, then once all the text was deleted when the file was closed and/or a new one re-loaded, all those marks ended up on the first line, and the Text widget choked. Now dialogs can have a reset method that cleans up after them, and it is called when the dialog is destroyed.
Fixes #203
Fixes #200
=> Close dialogs when file is closed or opened

src/guiguts/application.py
On a Mac, user would like `Cmd+w` to close the dialog with focus. If the focus is in the main window, then it should close the currently loaded file, and not close the main window.
=> Make `Cmd+w` close dialog/file as expected

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/mainwindow.py, src/guiguts/page_details.py, src/guiguts/search.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
In particular this is to consolidate the need for Mouse-3 to be interpreted as Mouse-2 and Control-Mouse-1 on Macs. Previously, these were done in different places, and not all places did both bindings.
One place that may not have had support for Control+1 (one-button mouse equivalent of right-button) is popping the context menu in text widgets on Macs. May have got away with it through default Mac behavior.
=> Centralize most of the mouse binding

src/guiguts/search.py, src/guiguts/word_frequency.py
Problem occurred when dialog was already visible, with a message showing, e.g. the latest Count, then was displayed "again" with a new word in it, either from a word selected in the main window, or from the WF dialog. In both cases, dialog message needed clearing.
Fixes #204
=> Clear Count message when S/R dialog shown

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/page_details.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
1. Default tooltip position is centered below widget
2. If tooltip would extend off the left or right of screen, it is kept on screen by shifting it right or left.
3. If tooltip would extend below bottom of the mainwindow or dialog that contains the widget, then tooltip is centered above widget instead of below.
4. Accepts string which can contain newline characters for multi-line tooltip.
5. Added to status bar items and to the page details dialog which is accessed by right-clicking the "Lbl" button in the status bar.
6. Other tooltips will be added as new features are added.
=> Implement tooltips

src/guiguts/maintext.py, src/guiguts/utilities.py
Some text files and good/bad words files may still be ISO-8859-1 rather than UTF-8. Try to read them as UTF-8, and if they fail, read them as ISO-8859-1.
=> Read ISO-8859-1 files from DP correctly

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/preferences.py, src/guiguts/utilities.py
1. Avoid using right button. Use left button for main feature, and Shift-left for additional feature if needed.
2. Move "Choose image scans dir" to File-->Project menu, so no longer available by clicking status bar. It is popped automatically anyway, if the user tries to look at a scan before it is set up. GG1 has a File-->Project menu button for it too.
3. Add Shift-click to the ordinal button to toggle the display of the character name. Some users find the changing length of the button distracting, and it would take up too much space to make it long enough to fit the longest common character names. Setting is stored in GGprefs file.
Fixes #210
=> Simplify status bar clicking

src/guiguts/preferences.py
An assertion is too annoying for developers and testers, because if you run a "later" release, it saves a new PrefKey in the Prefs file. Then when you run an "earlier" version, it reports that the new PrefKey it loads from the Prefs file is invalid.
Downgrade it to a warning, which will appear in the terminal, since it happens before the GUI has been initialized.
=> Downgrade invalid PrefKey message

src/guiguts/application.py, src/guiguts/page_details.py, src/guiguts/widgets.py
When it's modal, you can't scroll the text up and down to help decide what values you want to set in the dialog.
Change OkCancelDialog to OkApplyCancelDialog which has an Apply button that applies the changes made so far in the dialog. Use this new dialog for Page Label Config.
Note that (like other apps) once you click Apply, those changes are applied and can't be canceled by clicking Cancel. The OK button is equivalent to Apply followed by closing dialog.
(Note: nested modal dialogs are not implemented well in tkinter - when the dialog popped another to ask the page number, the dialog became modeless once the page number was entered.)
=> Change Page Label Config dialog to modeless

docs/index.rst, src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
1. Menu Edit-->Preferences pops the dialog on Windows/Linux, and the standard application menu Settings entry pops it on a Mac.
2. Currently has 2 tabs (one of which is currently empty)
3. Line numbers, Auto Img, and Bell settings implemented.
4. Existing Preference callback feature utilized and extended to be called whenever preference changes. This means preference can be used to set/query the value, rather than needing a separate variable and/or set/query functions.
5. Should be able to change tabs in the dialog by using Ctrl-tab (maybe Cmd-tab on Macs?) and by using Alt+first letter of tab name (probably not on a Mac).
=> Add a Preferences dialog

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/file.py, src/guiguts/mainwindow.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/project_dict.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/pptxt.py, src/guiguts/utilities.py, src/guiguts/widgets.py
1. Either sort by line.column or by "Alpha/type", which means an alphabetic sort where appropriate, or grouped by type of error.
2. CheckerDialog provides default sort routines, but specific tools can define their own, like Basic Fixup.
3. Checker messages are now distinguished into header, footer or content, with different sections - this is so that sorting knows which ordering to preserve, e.g. a header should come above content, regardless of sort order.
4. Project dictionary is now only saved if a word was actually added - previously it was saved even if word was already there.
5. This makes it possible to change the meaning of "process & remove all" to mean "(process & remove) all", rather than "process & (remove all)".
6. Previously selected message is reselected and displayed when …
=> Add sort options, etc to checker dialogs

src/guiguts/maintext.py
Logic in the code to store the previous selection did not take into account the case where there was a selection, and then it was cancelled, leaving no selection.
=> Fix "Previous Selection" bug

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/misc_tools.py, src/guiguts/spell.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/pptxt.py, src/guiguts/word_frequency.py
1. If tool is run on a document that has never been saved, then it does not have a "project folder" in which to put files like the project dictionary. So, check file has a filename before running the tool.
2. This required something I've been avoiding for a while - making the single File object accessible from all the higher level routines. Function `the_file` now returns the single File object (similar to how `maintext` works).
3. Unfortunately file.py imported spell.py in order to reset the current spelling dictionary, which was the wrong way round, in that the file shouldn't know about the spell check tool, but came about because of my previous reluctance to do point 2 above.
4. Now point 2 has been done, the spell checker keeps a record of which languages it has loaded, and resets if …
=> Ensure document has a filename before running tool

src/guiguts/checkers.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
For now, just tooltips need to be deleted when a dialog is destroyed, because the tooltips are Toplevel widgets in their own right, so are not automatically destroyed when the widget they belong to is destroyed.
Register each tooltip of a child of a TopLevelDialog, and when that dialog is destroyed, destroy the tooltips.
=> Tidy up when dialog is destroyed

src/guiguts/maintext.py
Where a key press was handled too early (perhaps keystrokes that are bound to the class rather than the instance) it did not then also trigger the KeyPress event binding that updates the line numbers. Using KeyRelease instead works fine, and is the simplest and safest fix IMO.
Fixes #228
=> Ensure line numbers are updated

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
Same behavior as Guiguts 1, as documented in the manual: https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Tools_Menu#Rewrapping
More tolerant regarding blank lines than GG1, e.g. if no blank line before/after markup or between nested markups, it should still work correctly.
Only blockquote markup can have other markup nested inside.
Wrapping margins can be set in the Prefs dialog, or as described in the manual, can be overridden using markup for some types, e.g. `/#[8.4,68]`
At present, rewrapping uses the "greedy" algorithm (via the standard python `textwrap` module), that used to be in GG 1.0.25. The other (Knuth-Plass) algorithm that was in GG 1.0.25 may be added to GG2 at a later date if desired.
FIxes #54
=> Add rewrap functionailty

src/guiguts/application.py, src/guiguts/maintext.py
1. Allow user to Shift-click with Option/Alt key pressed to make a column selection. So, user can click at start, then Shift-click to make a regular selection. Or, click at start, then Shift-Alt-Click (use Option instead of Alt on Macs) at end to make a column selection. Multiple Shift-Alt-Clicking may not do what you expect due to ambiguity over the start/end points of the selection - you have been warned!
2. User can Shift click the Selection label in the status bar to switch selection from a regular selection to a column selection.
Fixes #239
=> Improve column selection

src/guiguts/maintext.py
When a column select operation scrolled such that the longest line went off-screen, the calculations attempted to get the bounding box of that line, causing the error. Now only get the bounding box when the line is visible.
Fixes #237
Does not tackle any other column select issues.
=> Fix assert failure when column select dragging

src/guiguts/maintext.py
Operations like Search make the found line visible. However the built-in routine that does this only make it visible, not central, so it may be the first or last line in the window, meaning user has no context lines around it.
Fixed by repeatedly seeing lines ever further from the desired line up to half the window height, which leaves the desired line in the middle of the window.
Fixes #244
=> Position "seen" line better in window

src/guiguts/application.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/widgets.py
1. Menu entry added to Tools menu.
2. Behavior generally similar to GG1
3. "Auto Fix" option is like "99% Auto" in GG1, but a more conservative when there are hyphens or hyphen-asterisks before/after the page separator. These need a human eye.
4. Reason for Undo/Redo buttons is that these need to normal undo/redo but then to re-view the first page separator that needs fixing, which a simple Undo/Redo can't do.
5. The "undo block" methods will be replaced by more general MainText methods at a later date. The idea is that a single "undo/redo" will undo/redo all the changes made by the last mouse click.
6. Various key bindings have been set up, to mostly match or augment those in GG1. In Windows, at least, the buttons have and underline under the character that will work as a shortcut when …
=> Implement Page Separator Fixup

src/guiguts/maintext.py, src/guiguts/tools/jeebies.py
The he/be fixing code (via Ctrl-click) only worked for lowercase he/be.
Only "be" was converted to "he". Any other he/be word ("Be", "HE", "bE", etc.) was converted to lowercase "be".
Also (since most, but not all, in jeebies code) silence warnings from latest version of pylint, mostly by passing arguments into nested helper functions, rather than relying on access to variables defined in the outer function. It does make the functions clearer too, IMO.
=> Hebe fix bug

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/utilities.py, src/guiguts/widgets.py
1. Unmatched block markup (copes with `/#` being nestable but other types not nestable). 
2. Unmatched brackets (not nestable)
3. Unmatched curly quotes (not nestable)
4. Unmatched DP markup (not nestable)
5. "Nestable" above means that it will permit `/#` to follow `/#` without an intervening `#/`, for example. But it complains about `[` followed by `[` without intervening `]`. It would be possible to change which are nestable and which are not, but this matches GG1 behavior.
6. First enhancement compared to GG1: you can use upper/lower case indiscriminately for block markup  - in GG1, if you use upper case to open, e.g. `/C`, you must use upper case to close.
7. Second enhancement is that it checks that the matching block markup is at the start of a line. In GG1, if you open with `/C`, …
=> Add text file "Unmatched..." checks

src/guiguts/misc_dialogs.py, src/guiguts/word_frequency.py
1. Missing tooltip in word frequency dialog word list.
2. Remove periods from Prefs dialog spinboxes.
=> Fix a few tooltips

src/guiguts/application.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py, src/guiguts/root.py
Note that GG2 will need to be restarted after changing this Pref. All the menus would have to be deleted and recreated, which is just not worth the time or code complexity for something that most users will use once (or never).
=> Add Pref for Tear-Off menus

src/guiguts/checkers.py, src/guiguts/word_frequency.py
If the focus is on the checker dialog, and up/down arrow is pressed, it should select the previous/next line in the dialog.
On Macs, selecting a line didn't force focus to the main text window anyway. This commit also doesn't force focus for other platforms if the selection was changed by arrow key (otherwise, you have to refocus on the checker dialog to hit the arrow key again).
Note that Ctrl+arrow key, etc., do not do the processing, fixing, deleting all similar, etc., that can be done with the mouse. This is only for browsing through the errors.
=> Allow selection in checker dialog with arrow keys

src/guiguts/misc_tools.py
Badly formed markup can easily give false "unmatched markup" errors, so add a check for bad markup to the Unmatched Block Markup check.
Also, improve "Alpha/Type" sorting in this dialog. It now lists all Bad Markup first (since likely to be the problem), then all Unmatched Markup). Within those categories, it is sorted by the type of markup, e.g. blockquote, poetry, index, etc., and within those subcategories, "open" markup comes first, then close markup, and finally, if all those are equal, e.g. two "#/" markups, they are ordered by their location in the file.
=> Add badly formed markup check for block markup

src/guiguts/widgets.py
If the user closes the dialog with the Escape key, there might be a tooltip currently showing. Although the code attempted to destroy any visible tooltips, it failed to do so if the parent widget had already been destroyed (NTS: Avoid `suppress`ing Tk exceptions)
Also if the user Escaped out of the dialog in the 1 second gap before the tooltip was shown, it caused a traceback, again because a destroyed parent was being referenced.
=> Fix tooltip bugs when Escaping out of a dialog

src/guiguts/application.py
The Search menu's docstring and variable names seem to have been copy/pasted from init_view_menu; just some cleanup.
=> Fix labels / variable names in search menu

src/guiguts/misc_tools.py
I put a method in there temporarily until I had the full version completed and merged. Replaced with the
full version from `maintext`
=> Remove PageSepDialog's `undo_block_begin`

src/guiguts/application.py, src/guiguts/misc_tools.py
1. Works on selection if there is one (including column sel).
2. Works on whole file if there is no selection.
3. Submenu of Tools menu.
4. "Unicode" only converts those that have a unicode fraction character representation
5. "Unicode or super/sub" uses the Unicode character if there is one, or uses superscript/subscript.
6. "Super/subscript" uses super/subscripts for all.
7. Should convert "-1/2" to "-½" (unlike GG1)
8. Won't convert "B-1/2" or "B1/2" as they are more likely to be plate numbers or similar.
=> Add Convert Fractions feature

src/guiguts/checkers.py, src/guiguts/search.py
Displays the first non-blank line of the match.
Example regex: `^\nabc`
This will match a newline followed by `abc`.
Without this fix, just the newline (i.e. blank line) is shown in Find All dialog. With this, the line beginning `abc` should be shown, and `abc` should be highlighted.
=> Display multi-line Find All searches better

docs/index.rst, src/guiguts/application.py, src/guiguts/footnotes.py
Since footnote fixup is a large task, split it into pieces.
This piece just lists all the footnotes and anchors in a Checker Dialog.
Algorithm is to find occurrences of "[footnote", allowing capitalization & space variation. For each one, get its label, e.g. "4" in "[Footnote 4:", then search backwards for an anchor that matches it. Don't use "/#[4]" though, because that defines width parameter for block markup.
Each anchor or footnote is added to the checker dialog, and the whole footnote should be highlighted when the line in the dialog is selected. Note that one level of nested square brackets is permitted inside a footnote, i.e. a footnote starts & ends with square brackets, and may contain open & matching close square brackets, but not brackets within those brackets.
Sort by …
=> Add first part of Footnote Fixup

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py
In order to align better with GG1...
1. Adjust the highlight color to gold.
2. Page separator lines take precedence over location of page boundary set in project json file.
3. Page marker flags take precedence over page sep lines.
Linked with GG1 PR: https://github.com/DistributedProofreaders/guiguts/pull/1298
=> Adjust handling of page marker flags

src/guiguts/checkers.py, src/guiguts/footnotes.py
1. If a footnote has no anchor
2. If two footnotes have the same anchor
2. If the anchors/footnotes are out of sequence with each other. Note that the actual numbers don't matter, e.g. if anchor 2 appears before anchor 1, it's OK as long as footnote 2 appears before footnote 1, but not if footnote 2 appears after footnote 1.
Fixes #275
=> Add error checking to Footnote Fixup

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/search.py, src/guiguts/widgets.py
Shortcut is `Ctrl/Cmd+semicolon` or use the Tools--> Unicode menu.
The only sequences defined so far are:
1. Up to 4 hex digits - dialog closes when 4 are typed.
2. Hex digits can optionally be preceded by `x`, `U+`, etc.
3. Or use `#nnn` where `nnn` is any number of decimal digits. Use Apply/OK to terminate these.
=> Add compose sequence dialog

src/guiguts/maintext.py
This stops it from moving page boundaries to the beginning of the region selected for case changing.
Fixes #283.
=> Use new replace for case change

src/guiguts/checkers.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/search.py, src/guiguts/word_frequency.py
Previously, when a PersistentBoolean/Int/String (which are inherited from Tk.Variables) was set, it also set the linked GG Pref value. This puts the reverse linkage in, which means that if a separate piece of code updates a Pref, then the Tk variable will be updated, and any associated checkbox, etc., will be updated too.
This removes the need to have dialog class variables to the Pref setting.
Should be no change in behavior.
=> Simplify use of Tk Variables & Prefs

src/guiguts/widgets.py, src/guiguts/word_frequency.py
When Case Ignore is on, words that are ALL CAPS, Initial Caps, or MiXeD cASe aren't detected, which could
confuse the user. Therefore disable those buttons when Case Ignore is on, and enable them when it's off. Display a tooltip to explain to the user if they are disabled.
Fixes #289
=> Disable WF case buttons if `Case Ignore`

docs/index.rst, src/guiguts/application.py, src/guiguts/highlight.py
Add ability to highlight single or double quotes in the current selection, and to remove current highlights. Based on GG1's behavior. All 3 are available as menu items in the Search menu.
Testing notes:
- Select some text, then choose each item from the menu
- Modes are exclusive; highlight single, then double, will un-highlight single before highlighting double
- Remove highlights should remove any current highlights
- Both straight and curly quotes are supported
- Column selection is supported
- If you select text, highlight, then select different text (even if they overlap) and highlight again, old highlights are removed first, then new highlights in the selected area applied.
- Choosing the menu item with no selection in effect, does nothing
All of these behaviors are based on GG1's …
=> Highlight single/double quotes in a selection

src/guiguts/application.py, src/guiguts/preferences.py, src/guiguts/root.py
There is a bug/limitation in how the geometry of the root window is reported when the window is maximized (at least on Windows). It reports that the window is the size of the full screen, but that the top left corner of the window is wherever it was before maximizing.
This means (like GG1) that when you quit and restart, GG2 starts with its top left somewhere on the screen, but the size is the full screen size, so some of the window vanishes off the bottom & right.
Fixed by also saving the "state" flag (which is normal or zoomed) and restoring that when the program is
restarted. Also, not saving the bad geometry (i.e. big window but not at top-left) reported after maximizing.
Fixes #302
=> Preserve geometry of maximized main window

src/guiguts/application.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py, src/guiguts/widgets.py
This adds fractions, various other characters, quotes, super/subscript numbers, and Greek characters.
Also adds a Help-->Compose Sequences dialog, which lists all valid compose sequences, and allows the user to click on a letter in that help to insert it directly.
=> Add remaining compose sequences

src/guiguts/maintext.py, src/guiguts/utilities.py
If parameters are the same, wrapping behavior should now be identical to GG1.
This PR does not affect processing of block markup, just the actual wrapping of the words.
=> Implement Knuth-Plass wrapping

src/guiguts/file.py
When clicking on `Img:` in status bar, allow user to type `3` when image name is actually `003`, up to 4 leading zeroes.
This mimics GG1 behavior.
Fixes #307
=> Allow leading-zero omission in Goto Image

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/page_details.py
When user clicks on a row in the dialog, jump to the page in the file, so user can see the text there to aid their decision about which type of page it is. If user has Auto Img turned on, the image will show in the image viewer.
Fixes #295
=> Show image from page label config dialog

src/guiguts/application.py, src/guiguts/maintext.py
If file path is too long, truncate it to the left, leaving the filename still visible.
=> Restrict width of file path in title bar

src/guiguts/file.py, src/guiguts/page_details.py
Add the info necessary to construct the labels when in GG1. Format is `[ImgNNN|Arabic|+1]`
"Arabic" can be "Roman"
"+1" can be "No Count" or a page number
This version must be used in conjunction with a version of GG1 that has the added info - it won't work with older versions of GG1, like 1.6.2.
[GG1 PR#1308](https://github.com/DistributedProofreaders/guiguts/pull/1308)
=> Add page label info to page marker flags

src/guiguts/footnotes.py, src/guiguts/maintext.py, src/guiguts/misc_tools.py
When using python 3.12, flake8 reports that some
arithmetic operators (inside braces inside formatted strings) do not have spaces around them.
It's correct - they didn't.
=> Fix flake8 error messages

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/utilities.py
1. Use "Folder" on macOS, not "Directory" in menu buttons
2. Use `projectID0123456789abc_comments.html` file to extract project ID, and save it in the project json (bin) file.
3. When user turns on Auto Img or tries to load an image for the first time for that project, first look if there is a `pngs` subdir in the project dir. If not, is there a subdir `projectID0123456789abc_images`?
Fixes #328
=> Improve scan directory handling

poetry.lock, pyproject.toml, src/guiguts/preferences.py
User's "documents" folder is not necessarily `~/Documents`. This may be because the user has set its location, but is most likely because Windows has sneakily placed the documents on OneDrive and the user has given up
battling against it.
So, interrogate Windows to find the actual location of the Documents folder (which may not even be called `Documents`) and use that.
On all platforms, if the GGprefs folder doesn't exist, create it, and also create any parent folders that are necessary, e.g. if user's documents folder is
`~/Documents` but that folder doesn't exist, then
create `Documents` first, then the GGPrefs folder
within that. Should never happen, but just in case! Also, if folders can't be created, or the Prefs file can't be saved, output an error, rather than crashing with an …
=> Improve placing of GGprefs on Windows

src/guiguts/application.py, src/guiguts/preferences.py
When `--nohome` is specified, prefs are not loaded from the prefs file, and also not saved if preferences are changed.
=> Add `--nohome` argument

src/guiguts/checkers.py
Use the colors of selected text in the main window.
Fixes #349 (the problem raised in point 1 in that issue is already handled by the tool).
=> Make highlight in checker dialogs clearer

src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/utilities.py
If the paragraph input to the text wrapper didn't have a newline, then the output wrapped paragraph shouldn't have one either.
Fixes #347
=> Don't add newline when rewrapping

src/guiguts/misc_tools.py
Only check `i|b|u|g|f|sc` markup, rather than any "word"
=> Restrict Unmatched DP Markup check

src/guiguts/misc_tools.py
If fraction convert is done on a selection, make sure the selection is correctly preserved, using the new feature added by PR #351.
Also position insert cursor directly after last fraction converted.
Fixes #358
=> Improve user feedback after fraction convert

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/highlight.py, src/guiguts/preferences.py, src/guiguts/spell.py, src/guiguts/word_frequency.py
1. If user has selected text, spell check will just check the selected words (or part words if word is not wholly within selection). Note that GG1 Spell **Query** does not have this feature, but Spell **Check** does.
2. If word appears more times in the file than the threshold value, it is assumed to be a good spelling and so is not reported - this is the same as GG1's Spell **Query** but Spell **Check** does not have this.
.
=> Spell check

src/guiguts/application.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py
For bracket and curly quote unmatched checks, there is now a checkbutton that allows the user to control
whether nesting is permitted, e.g.
`[Footnote: [**proofer note] text of footnote]`
User can change the setting and re-run.
Fixes #326
=> Provide nesting control in some unmatched checks

src/guiguts/checkers.py, src/guiguts/widgets.py
Instead of showing "0 entries" when dialog is created or process is re-run, show "Working..." instead.
=> Show "Working" in checker dialogs

src/guiguts/checkers.py
Checker dialog unsets marks and removes spotlights when it is destroyed. If the user closes the main window without closing the checker dialog first, then by the time the checker dialog is destroyed the main window no longer exists, so causes errors unsetting marks, etc. Check main window exists before tidying up.
=> Check main window exists when closing checker

src/guiguts/footnotes.py
If a footnote is a continuation from a previous page, it will be marked as a suspect in the Fixup dialog.
When that footnote is selected in the dialog, then "Join to previous" can be used to join the footnote with its parent.
At the moment, assumes footnote is well-formatted, and if it is not, the feature might not work.
Also fix bug that selected the wrong section when a footnote did not start at the beginning of a line, e.g. when preceded by `*`
=> "Join to Previous" Footnote feature

src/guiguts/tools/jeebies.py
Fixes issue #367. The "Check Level"
buttons no longer re-run Jeebies when
clicked. They just set the check level
and the user then clicks "Re-run" to
apply the Jeebies check at that level.
=>  Fix Jeebies "Check Level" radio button behaviour

src/guiguts/word_frequency.py
1. Make focus default to list of words, except when user is typing in the threshold or regex field
2. Home & End keys go to first/last entries, like GG1
3. Arrows and Page Up/Down should scroll list
4. Typing a character jumps to the first word in the list that begins with that character, like GG1
Fixes #374
=> Improve navigation in WF dialog

src/guiguts/maintext.py
If the code moved the insert cursor, but the window didn't need to scroll because of it, it didn't trigger the update code.
Fixed by overloading the mark_set method and catching the case where it's the insert cursor.
=> Highlight current line always

src/guiguts/widgets.py
If characters are selected, delete them before inserting the character created by the compose sequence.
Fixes #383
=> Delete selection when inserting compose sequence

src/guiguts/search.py, src/guiguts/widgets.py
Since these fields typically have the same type of text as the main window, let them share the font.
Fixes #389
=> Use main text font for S/R fields

src/guiguts/file.py, src/guiguts/highlight.py, src/guiguts/maintext.py, src/guiguts/misc_tools.py, src/guiguts/search.py, src/guiguts/utilities.py, src/guiguts/word_frequency.py
To avoid bugs and limitations in Tcl regexes, slurp the relevant part of the file into a python string and do the searches there before converting the match locations back into line/col format as needed.
Also fix bug in Replace where word boundaries, and look-ahead caused Replace to do nothing even though the match had been found.
This affects, Search, Replace, Search & Replace, Count, Find All and Replace All.
Could potentially affect WF, where you click a word and it takes you to the location in the file.
Fixes #266 
Fixes #297
=> Use python regexes in Search/Replace

src/guiguts/maintext.py, src/guiguts/search.py
If Search & Replace strings have same number of lines, then replace line-by-line so that page break marks remain on the correct line.
Fixes #282
=> Improve page marker positions for S/R

src/guiguts/maintext.py
Replace routine hadn't been code to allow for a "mark" being passed in as an index.
=> Avoid traceback using Ctrl-left in Basic Fixup

src/guiguts/application.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py, src/guiguts/widgets.py
In Tools->Unicode menu.
Also doubles as "Commonly-used characters" dialog, by using the first entry in the dropdown. It should remember which block was shown the last time the dialog was shown. Clicking a character should insert it. Hovering over a button should show a tooltip with the character ordinal & name.
=> Add Unicode Blocks dialog

src/guiguts/maintext.py, src/guiguts/search.py
1. Highlight next match correctly when using Replace & Search
2. Count regexes with backreferences (or lookarounds) correctly
3. Replace All with backreferences (or lookarounds) correctly
4. Search backward for regexes with backreferences (or lookarounds)  correctly
Fixes #395
Fixes #396 
Fixes #398
=> Regex bugs

src/guiguts/checkers.py, src/guiguts/search.py
Show newlines as `⏎`
Fixes #413
=> Improve display of multiline Find All display

src/guiguts/maintext.py, src/guiguts/search.py
1. Change text color to red if current string is invalid regex.
2. Display regex compilation error if user still tries to use a red (bad) regex.
=> Trap bad regex in S/R dialog

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/root.py
Checkbox used for Dock/Undock was initialized with a bool instead of a tk.Boolean.
Also removed use of literal strings for settings.
=> Dock/Undock Image Window without errors

src/guiguts/search.py
Slightly less dark red for light themes, and a slightly lighter red for dark themes
=> Adjust bad regex colors slightly

src/guiguts/application.py
Previous edit meant the preceding hyphen was still shown, even if there was no filename.
=> Tidy title bar when no filename

src/guiguts/maintext.py, src/guiguts/search.py
Instead of only matching "end of string" (where string could be just the selected text), match any "end of line",
and only "end of string" if it's also "end of line".
Should match treatment of `^`
Fixes #419
=> Dollar fix

src/guiguts/application.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
User can either type words (e.g. "capital latin") and find all Unicode characters that contain all those words in their name. Or they can type a hex code point number, e.g. "a9" for the copyright sign.
Clicking on the character/name in the list will insert the character; clicking on the block name will open the Unicode block dialog.
Note: The warning symbol ⚠ (non-emoji version) will appear next to a character's name if the character was added to Unicode after version 3.2 (March 2002)
=> Add Unicode Search dialog

src/guiguts/search.py
Output the error in an error box and the message log without a full stack trace.
Fixes #423
=> Trap python errors in `\C...\E` more neatly

src/guiguts/misc_dialogs.py
1. Stop it being resizable - it shouldn't be.
2. Move warning about theme change requiring restart into "Theme" label so it's obvious what it refers to.
=> Minor Prefs dialog improvements

src/guiguts/maintext.py
If focus was in peer, then a dialog was popped, then the Split Screen was turned off, the peer was hidden, but was still the "active" window, causing odd behavior. Not sets the focus, and hence active, window to be maintext.
=> Return focus to main text when peer is closed

src/guiguts/word_frequency.py
Some modes don't have Suspects, so the "Suspects Only" checkbox was confusing.
=> Hide Suspects only when not relevant in WF

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py
1. Store position & size of floated viewer
2. Store sash position for docked viewer
3. Store zoom scale factor
4. Add Dock toggle and Close button to viewer
5. Turn off AutoImg if user closes viewer
6. Use opacity=75% to soften contrast in viewer
=> Improve image viewer

src/guiguts/application.py, src/guiguts/misc_tools.py
Pops a list of occurrences of `[**`
Because it is likely that user might want to do other checks while resolving proofer comments, the new dialog is independent of other checkers, so can be shown at the same time as Find All, Jeebies, etc
Fixes #356
=> Add "Find Proofer Comments" to Search menu

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py
Saves a copy of the current file, but does not change the current filename, nor the "edited" flag.
Name of saved copy does get inserted in the "Recent Documents" menu.
Fixes #459
=> Add "Save a Copy As" menu option

src/guiguts/mainwindow.py
Redirect the undo/redo events from the read-only text list in checker dialogs to the main text window.
Fixes #446
=> Make undo/redo work from checker dialogs

README.md
Either 3.11 or 3.12 work for users, and it's easier to find 3.12 to download from the website for Windows
=> Update README to mention Python 3.12

src/guiguts/checkers.py, src/guiguts/word_frequency.py
All checker dialogs and WF dialog now use the same font as the main text window.
Fixes #480
=> Use text font for checker dialogs

src/guiguts/word_frequency.py
First, don't jump in main text with WF letter shortcut.
Just show the first word that starts with the given letter, but don't move the main text to show the location. That only happens if the user clicks on a WF word.
Fixes #482
Second, Make WF count & search consistent.
It was counting, but not searching for phrases like `<i>c</i>4`, i.e. where there was a word character immediately before/after the marked up phrase. The `<i>c</i>` should not be found by word count because it is not a word - the "word" is `c4`.
Fixes #476
=> Two WF fixes

src/guiguts/maintext.py, src/guiguts/spell.py
If spelling error was preceded by single straight quote, code did a second check to see if the word was in the dictionary without the quote (to cope with the case that the quote might be an apostrophe `'tis` or an open quote from speech, etc. However, it didn't correct its notion of where the word was on the line to account for the (now missing) quote. It therefore highlighted the line one space too far left.
Also, noticed during testing & fixed, if the last line of file didn't have a terminating newline, spell check didn't spell check that last line.
Fixes #477
=> Correctly locate spelling errors with single quote

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/spell.py
Button in spell check dialog allows current word to be added to the user dictionary for the main language, e.g. `dict-en-user.txt`. Button shows the language to avoid confusion.
Fixes #481
=> Add ability to add spelling to global lang dict

src/guiguts/maintext.py
This is already default behavior for Windows/Mac, but not for Linux.
Common code used for all platforms to aid future
maintenance. It's harmless on Windows/Macs.
=> Explicitly delete selection during paste

src/guiguts/mainwindow.py
There are 4 combinations: dark/light theme combined with image inverted/not.
This ensures all 4 look reasonable by using a different alpha (transparency) value for dark/light themes.
If needed we could use different values for whether the image is inverted or not, and have 4 different alpha values.
Fixes #499
=> Use different image alpha for dark/light themes

src/guiguts/search.py, src/guiguts/widgets.py
Fixes #506
If font size was too large, and S/R dialog too short, then underscores wouldn't fit in the field because the fields resized vertically with the dialog. Now they don't.
=> Make S/R fields tall enough

src/guiguts/search.py
1. Cmd/Ctrl+Enter does Replace & Search for next occurrence the same as GG1
2. Shift+ Cmd/Ctrl+Enter does Replace & Search for previous occurrence, which is different to GG1, but consistent with using Shift for reversing the search direction
3. Also fix bug with Shift-clicking R&S buttons
=> Add missing S/R key shortcuts

src/guiguts/misc_dialogs.py
1. Add `/#` to tooltip for blockquote settings
2. Add `Nowrap` to label for block settings
3. Remove `/P` from tooltip for block settings
=> Fix and clarify block wrap preferences

src/guiguts/application.py, src/guiguts/file.py
Remove all `/*`, `*/`, `/#[12.5]`, etc from the file, once file has been rewrapped.
Note that if an open wrap is followed by a blank line and another open wrap, the blank line is only there because of limitations in some PPing tools, not because the blank line is needed. Therefore, like GG1, the blank line will also be removed.
Example:
```
/#
/*
poetry
*/
All inside blockquote
#/
```
=> Add "Clean Up Rewrap Markers" feature

src/guiguts/application.py, src/guiguts/data/scannos/en-common.json, src/guiguts/data/scannos/regex.json, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/search.py
Two scannos files are included with the release:
regex.json and en-common.json, which are based
on the GG1 versions.
The user can also load their own scannos file. The recently loaded scannos files are in a dropdown at the top of the dialog.
The first scanno is shown, and the user can click Next or Prev. If there are no occurrences of the next/prev scanno, it autoadvances until it finds a scanno that does occur, or it hits the end/start of the scannos file.
All occurrences of the scanno are listed, and the
replace button (or Cmd/Ctrl left mouse click) will do the replacement if one is specified in the scannos file.
Scannos can also have an optional hint to explain what they do, which is displayed in the dialog.
=> Add Stealth Scannos feature

src/guiguts/highlight.py
In order for enum.auto() to work here using StrEnum, the class can only contain these auto-string variables; the dicts for color definitions have to be separated.
=> Class refactor needed to prepare for #42

src/guiguts/application.py, src/guiguts/highlight.py, src/guiguts/maintext.py, src/guiguts/preferences.py, src/guiguts/root.py, tests/test_guiguts.py
Fixes #42 
Adds:
- `bool` preference for highlighting quote marks and brackets
- toggle in the Search menu to turn pref on and off
- 500ms repeating event to do the highlighting work
Highlights the following pairs:
- parens `()`
- curly brackets `{}`
- square brackets `[]`
- straight single and double quotes `''`, `""`
- curly single and double quotes `‘’`, `“”`
- single and double angle quotation marks (aka guillemets) `‹›`, `«»`
- single and double "high-reversed-9, low-9" quote marks (‘nines’) `‛‚`, `‟„`
I created a test file for your convenience (which I'll attach to this PR). In the text file, put your cursor on the all-caps word in the middle of each paragraph for easy highlighting of a bunch of bracketing pairs.
I'm especially interested in feedback on the colors, including in the …
=> Highlight quote marks & brackets

src/guiguts/application.py, src/guiguts/highlight.py, src/guiguts/maintext.py, src/guiguts/root.py
Adds "Highlight Alignment Column" to the Search menu. This should work the same way the GG1 feature did: when activated, whatever column the cursor is on will be set as the alignment column and highlighted with a color, until turned off.
I re-used the same color as GG1 in light mode, and chose a more muted shade for the dark theme.
(Marking this as a draft for now; until #519 is merged, this PR will have all the diffs from that PR, because this branch is based on that other branch.)
Fixes #43
=> Highlight alignment column

src/guiguts/highlight.py
Move highlight color decision down the stack to `_highlight_configure_tag()`. Note that this only affects highlight.py; the base window colors and things like the color of selected text are out of scope here.
- Light theme: uses "Light" colors
- Dark theme: uses "Dark" colors
- Default theme: detects light/dark OS mode using `is_dark_mode()` and chooses Dark or Light colors.
If we adopt this we won't need to define Default colors for each tag type in highlight.py anymore; just Light and Dark.
Testing notes:
Using Default theme, open a document and set an alignment column (that's easiest because the coloring changes between themes). Then change the OS to the other mode and the window should change (at least it does in macOS). The highlight will not immediately change because it is …
=> Dynamically detect dark/light mode for "Default" theme

src/guiguts/highlight.py, src/guiguts/maintext.py
Subtly highlights the line the cursor is positioned on.
This tag is lowered to be below other tags, to avoid interfering with other highlighting. It may be that it should be the last thing run in `after_idle` for that reason.
(Marking as draft until #525 is merged)
Fixes #522
=> Highlight cursor line

.github/workflows/python-app.yml, src/guiguts/highlight.py
Add `--disallow-untyped-defs` option to mypy run.
Without this, it doesn't catch
```def highlight_aligncol_in_viewport(viewport: Text):```
which doesn't have a return type declared.
=> Make mypy stricter

src/guiguts/word_frequency.py
When the word pair was followed by punctuation, it wasn't detected.
Fixes #538
=> Fix hyphen / word pair WF failure

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_tools.py
Convert to curly quotes tries to convert all straight quotes to curly where it can be confident of which curly is needed. This normally leaves unconverted all those that should be open single curly, but  does a good job of most others. This is also
true with the equivalent GG1 and ppsmq tools.
Check curly quotes pops a dialog listing suspected quote errors such as quote at start/end of line or after/before space when curl is the wrong direction, or open quote preceded by word character, or paragraph end without closing double quotes (unless next para begins with double quotes), or unconverted straight quotes.
Dialog has several buttons that make corrections, and also supports Cmd/Ctrl+left/right click to make best guess fix, which is to convert to open curly if quote is straight, or to …
=> Convert to curly quotes & Check curly quotes

src/guiguts/file.py, src/guiguts/maintext.py
Rather than reconfigure highlight colors every time they're used, configure once at startup.
Rather than delete tags entirely every time we want to remove them from the UI, instead only remove the application of the tag (to text regions) and leave the tag itself defined (and configured with colors).
Define an order for highlight precedence, all in one place rather than scattered around the code.
Refactored a couple of instances of `"end"` to `tk.END`.
Fixes #537
=> Globally initialize highlight tags at startup

src/guiguts/maintext.py
If macOS clipboard contains non-text (e.g., an image) and user triggers smart_cut or smart_copy functions, TclError is thrown when TCL code "clipboard get" is run. Catch error and return from method if this happens.
Fixes #548
=> Catch edge-case exception in macOS clipboard

src/guiguts/maintext.py
The first row is always row 1; there is no row 0, so never return row 0 when examining the current viewport's range of rows.
Fixes #545
=> Never return a starting row less than 1

src/guiguts/maintext.py
=> Improve "highlight surrounding quote/bracket" behavior when a selection is active

src/guiguts/maintext.py
If at column 0, and trying to turn on alignment column, pop a warning window, and don't turn alignment mode on.
At any other column, behaves as before.
Fixes #557
=> Pop warning dialog if attempting alignment column at col=0

src/guiguts/maintext.py
Detect changes in theme and adjust tag colors.
Testing notes: just change the theme in any way, and it should work.
- Changing in GG preferences: should take effect immediately
- Changing OS dark mode: will have to interact with GG to trigger update
Fixes #555
=> Dynamically detect theme change

src/guiguts/misc_tools.py
Fraction failed to convert if previous line ended in a letter. This was due to surprising (to me) regex behavior where a dollar matches end-of-string OR a newline at the end of the string.
Fixes #563 
Almost certainly this was the inconsistent conversion failure noted in #384 by @okrick in lists of ingredients for recipes, most of which had lines ending with a period, so didn't trigger the bug - sorry for not managing to reproduce it then @okrick!
=> Fix fraction convert error

src/guiguts/maintext.py
Previously it converted the column selection to a
regular selection, then deleted it and inserted the typed character.
Now, it just deselects the text and inserts the
character as usual. This is not perfect, but is less surprising than previous behavior.
=> Fix bug when typing over a column selection

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
Adds a ruler along the top of each text view to display column numbers, highlighting current column number.
Adds a user preference to prefs panel (defaulting False) for control of this feature.
Fixes #61
**Testing Notes**
- Turn on column numbers in the preferences pane
- Ruler should scroll horizontally with its text view
- Using mousewheel / trackpad scroll in text area
- Using scrollbar
- I suggest testing at narrow and wide widths
- Also suggest testing just at the point where the horizontal scrollbar appears when you narrow the window just enough
- The ruler maxes out at 500 columns
- The ruler is only supposed to be drawn as long as the longest visible line
- UNLESS that line is narrower than the window. Then it pads to the window width.
- Colors should dynamically change in Default …
=> Add ruler to display column numbers

src/guiguts/application.py, src/guiguts/footnotes.py, src/guiguts/preferences.py
Does not include inline footnotes which will have a separate tool if that is required.
Implements the fast 2-pass version of 'Move FNs to Paragraphs' which uses marks.
Fixes bug caused by interaction with use of marks when last line of the file is a footnote.
Uses the elegant GG1 alpha() function to convert footnote labels to alphabetic form.
Unlike GG1 it correctly handles 'mid-paragraph' footnotes; that is, footnotes at the bottom of the page that are anchored in the paragraph above which continues on to the following page(s).
Footnote Fixup will work consistently before or after Page Marker removal.
=> Full functionality 'Footnote Fixup' tool

src/guiguts/checkers.py, src/guiguts/footnotes.py, src/guiguts/misc_tools.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/levenshtein.py
Due to the way it developed, the Checkerdialog
base class required tools that used it to set certain padding and columnspan to align. Fix this in the
base dialog instead.
Apart from minor adjustments to alignment, there
should be no behavioral change.
=> Simplify use of checker dialogs

src/guiguts/misc_tools.py
Don't convert fraction if preceded by period, e.g. the "2/18" in "4.2/18.6" should not be converted.
Fixes #572
=> Fix overenthusiastic fraction conversion

src/guiguts/maintext.py
Initialize the peer editor's colors at startup even if peer isn't currently visible. Otherwise in certain conditions, its theme won't match the other editor when the peer is made visible.
Fixes #576
=> Initialize peer colors at startup

src/guiguts/maintext.py
Watch click, drag, and click-release events; if currently dragging to select, and reaching the text widget boundary, scroll the view in that direction until the mouse is pulled back into the text widget. Event loop is discontinued when the mouse button is released.
This is only run on macOS, as it doesn't appear to affect Windows or Linux.
Fixes #238
=> Fix auto-scroll at window edge on Mac

src/guiguts/maintext.py, src/guiguts/utilities.py
For normal wrapping, the blank line is taken as a paragraph so is not itself wrapped. However, because indexes have been formatted into single whole lines, they are wrapped one line at a time. This accidentally included wrapping the blank lines. The wrapping routine hadn't been written to expect wrapping an empty string.
1. In lower wrapping routine, deal with an empty paragraph without raising an exception.
2. In upper index wrapping routine, only wrap lines that have text
Finally, while testing, I found an independent bug (of mine) which probably wouldn't occur in RL. I made a small index by deleting most of the lines from the example supplied, which left some page marks at the start of the closing `I/` line. It then failed to recognize this as the end of the index, and said "no match …
=> Fix exception wrapping blank line in index

src/guiguts/maintext.py
1. Column select now works in peer
2. Column select now works if text is scrolled right so that left-hand edge is off-screen
3. `rowcol` function now uses the focus widget, i.e. main text or peer. I thought previously it was OK to just use the main text, but if the index that is being converted to a rowcol is an `@x,y` string, it matters which widget you use to convert it. Symptom of
this failing was that if you scrolled the main text horizontally, when you started a column select in
the peer, the region actually selected didn't match the region dragged over - it was offset by the amount that main was scrolled horizontally. The function that has been changed is used *a lot*, but I'm hoping it won't have any effect on its other usage.
=> Fix column select failures

src/guiguts/file.py
This is to allow a PPer to load a ppgen file that has `.bn` commands in, and have page image files associated with the correct place in the file to aid continued work on the file.
It is not a solution to the issue of ppgen output files then being loaded by a PPVer using GG2.
=> Recognize ppgen `.bn` commands

src/guiguts/search.py
The First/Last button finds the first occurrence of the string in the file if searching forwards, and the last occurrence if searching backwards.
Note that searching backwards can be done by turning on "Reverse" checkbox. The currently selected value of "Reverse" is itself reversed if the First/Last button is Shift clicked, just like the Search button.
So, if "Reverse" is off, click First/Last for the first match, shift-click it for last match. If "Reverse" is on, click First/Last for last match and shift-click it for first match.
Since this behavior is identical to the Search button behavior, it should be intuitive to the user. If not, they don't need to use the Shift key and can just use the Reverse checkbox.
=> Add First/Last button to Search dialog

src/guiguts/misc_tools.py
Previously, only quotes that had 2 spaces either side were converted to ditto marks. Double quotes are now
interpreted as ditto marks if they are at start of line (with optional space before) and have 2 spaces after, or if they are at end of line (with optional space after) and have 2 spaces before.
This compromise is to try to detect ditto marks without letting badly spaced quotes pass by undetected, hence the requirement for a double space before/after/
=> Detect ditto marks better in curly quotes

src/guiguts/maintext.py
The blank lines had invisible characters to mark the page break locations - check for blank line didn't take this into account.
Fixes #600
=> Fix blank lines being lost during rewrap

src/guiguts/maintext.py
- Don't redraw ruler when pref is disabled
- Don't redraw peer's ruler when window not split
Also a couple of whitespace changes to mollify pylint.
=> Avoid useless redraws of column ruler

src/guiguts/maintext.py
In #238, binding of button-1 (left-click) created a regression that didn't fire redraws on click properly.
Fixes #613
=> Fix redraw handling (regression bug)

src/guiguts/maintext.py
Note that `undo_block_end` is called automatically when control returns to the user, so there is normally no need to call it in the application code.
Fixes #615
=> Undo case changes in one block

README.md
This new debug mode hadn't made it into the README.
=> Add "use default settings" VSC debug mode to readme

src/guiguts/maintext.py
Adds support for scrolling past the window edge in column select mode.
It's currently a bit imperfect / visually choppy; possibly that could be improved. But it seems to function properly.
I took the opportunity to simplify the non-column select mode scrolling to use less code. It should work the same as before, except I made the vertical scrolling a bit faster.
As before, the non-column select mode scrolling is only for Mac (because it isn't needed for Win/Linux).
The column select scrolling code is currently active on **all platforms**.
- Mac: because it's needed
- Windows: unknown (to me) - would appreciate feedback as to whether it was needed in the first place
- Linux: scrolling technically functions without this code, but it's **painfully** slow, so I opted to leave it on for Linux …
=> Column-select scrolling at edge of window

src/guiguts/footnotes.py
Move footnotes to paragraph end failed if the footnote itself had several paragraphs. Fixed by Quentin.
Fixes #611
=> Fix "move to para" bug with multi-para FNs

src/guiguts/maintext.py
Testing notes:
Load a file and run a WF check, e.g. hyphens (as noted in the original ticket). Clicking on a match will take you to that text in the file and highlight with SPOTLIGHT (e.g. orange background in light theme). Select one or more characters in the text. On the master branch, the cursor disappears and you can't see what's selected. On this branch, you can see what you've selected. (Should be the same if you select with keyboard or mouse.)
Fixes #631
=> Lower priority of SPOTLIGHT highlight tag

src/guiguts/maintext.py, src/guiguts/word_frequency.py
Because regexes include underscore in their idea of word characters, an occurrence preceded by underscore of a word found by WF would not be found by "whole word" search. So, the word would be listed in WF, but when the user clicked it, the word would not be found.
Fixed by changing search's "whole word" to wrap the search string with a more complex regex, rather than `\b...\b`
Also changed WF's idea of a word to include embedded underscores (in the same way as embedded periods are included), e.g. "i_001.jpg", but to strip leading or trailing underscores, which signify italics, e.g. "_dog_".
Fixes #628
=> Use consistent definition of word in WF

src/guiguts/tools/pptxt.py
Typo in regex caused text line `word...` to be reported as a "double punctuation" error.
Testing notes: lots of false positive "double punctuation" occurrences can be seen by running pptext on [the file from the linked issue](https://github.com/user-attachments/files/18286236/pptext.zip)
Fixes #624
=> Fix duplicate ellipsis/ double punctuation error from pptext

src/guiguts/application.py, src/guiguts/footnotes.py, src/guiguts/html_convert.py, src/guiguts/illo_sn_fixup.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/misc_tools.py, src/guiguts/page_details.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/levenshtein.py, src/guiguts/tools/pptxt.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
In any dialog (or main window) press F1 function key to bring up a relevant manual page.
Note that if your function keys are set up to perform other actions by default, you may need to press `<fn>+F1`, or something similar.
=> Implement F1 key to bring up manual page

src/guiguts/maintext.py
1. Exception on non-Mac platforms when using column select for first time due to non-initialized variable
2. Beginning drag before pressing modifier key didn't initialize everything that was needed, so when you dragged outside the window it reverted to slow
continuous scroll (mac-only)
=> Fix a couple column selection bugs

src/guiguts/maintext.py
Adjust scrolling speed during a drag-select operation based on how far outside the window we've moved.
For column-select mode, this affects all platforms. For linear select mode, it's only relevant on Mac.
Initial attempt:
- For vertical scrolling:
- Moving outside the boundary triggers a scroll operation every 500ms
- Moving at least 20 pixels beyond the boundary accelerates to 250ms
- Moving at least 40 pixels beyond the boundary accelerates to 125ms
- For horizontal scrolling, the delay is cut in half, so 250, 125, and 62ms.
**Edited to add:**
> Later this was changed to use a formula to scroll between 100-500ms (or 66-333ms for horizontal) depending on how far outside the viewport the mouse has moved.
This PoC will print debug info on output showing the current scroll speed (in ms) …
=> Scroll speedup

src/guiguts/tools/pptxt.py
Instead of reporting every occurrence of multiple spaces or multiple dashes separately, report once per line, with a count of how many occurrences, e.g.
`23.4: (x3) a ---- a ---- a ---- a`
Fixes #640
=> Compress pptxt report of adjacent spaces/dashes

src/guiguts/illo_sn_fixup.py
Moving a multi-line illo caused an exception.
=> Fix illo movement bug

src/guiguts/search.py
If unable to do a replace and search, most likely because the user already did a replace, then just do the "search".
Fixes #649
Testing notes: see issue
=> Improve behavior of "R&S"

src/guiguts/maintext.py
The main one I really want to see changed is the spotlight color, from `orange` to `darkorange`, at least for the dark themes -- white text just doesn't show as well on `orange` as it does on the `darkorange`.
The rest is playing around only for the colors for the dark themes to try to get better contrast between text color and background color. Some of what I did was to change the double-quotes to use related but different colors, and the straight quotes, ditto, and make them (for dark theme -- I didn't touch the light theme) a bit more noticeable.
It occurrred to me later that it might be better to have straight quotes' colors be related, and curlies' colors be related, but that can be a talking point.
My feelings will absolutely not be hurt if y'all throw up your hands in horror. 😁 (on …
=> Playing around with highlight colors.

src/guiguts/checkers.py
When Find All was done inside a selection, the spotlight match was hidden by the selection.
Fix by clearing selection when a spotlight is displayed, usually by clicking a message line in a checker dialog, also when the dialog is created.
Fixes #660
=> Fix Find All highlight priority

src/guiguts/preferences.py
Most likely reason is that a later release has removed a PrefKey (or potentially user has edited Prefs file). The previous message just said that the invalid PrefKey was ignored, which caused user concern. So, just output if in debug mode, so only devs see it.
Fixes #659 
Testing notes:
Easiest way is probably to edit the Prefs file and change a key, e.g. `auto_image` to `auto_imagx`. 
In master this will generate a warning. In this branch just a debug message (and nothing at all if not run with `-d` command line option).
=> Change "not a valid PrefKey" to a debug message

src/guiguts/file.py
First detect if the file is an HTML file, i.e. has the first line `<!DOCTYPE html>`
Also check if the filename currently has an extension. If no extension, or extension is `.txt`, then suggest `.html` for HTML files.
If no extension suggest `.txt` for non-HTML files. Use the suggested extension when pre-filling the
Save As dialog. User can override and set their own extension if they want to.
Fixes #651
=> Add default extension during File-->Save As

src/guiguts/maintext.py
Standard text thought breaks should not be rewrapped, because it turns
`       *       *       *       *       *`
into
`* * * * *`
Fixes #656
=> Don't rewrap thought breaks

src/guiguts/html_convert.py
Since first page mark may be at the very start of the master file prior to HTML auto-generation, and page markers have LEFT gravity, anything inserted at the start of the file would go after the first page mark. Then when the pagenum spans were added, the first pagenum span would be above the HTML header.
Fix by temporarily switching the gravity to RIGHT while the header is inserted.
Fixes #657
Also, make it work for multiple page marks at the top.
=> Insert HTML header above first page mark

src/guiguts/checkers.py, src/guiguts/illo_sn_fixup.py, src/guiguts/maintext.py
See [#668](https://github.com/DistributedProofreaders/guiguts-py/issues/668) for main attempt to solve this issue.
In this commit, if you do an undo/redo, the list of
messages in the illo/SN checkers is removed until you
manually click Re-run.
This is just to see what it's like, and what you think is
best. It would probably be possible (though more
complicated) to gray out the text instead of removing it
and intercept user attempts to click on the messages and
either do nothing or put up a message saying "you need to
re-run the tool".
=> Alternative to #668 (less-smart undo)

src/guiguts/checkers.py
Fixes #680
Testing notes: tested by me on Windows. @srjfoo - can you check it hasn't broken tools like Jeebies on a Mac please?
=> Stop checker dialogs being lowered after running

src/guiguts/illo_sn_fixup.py
When tool is first run, or re-run, select the first entry in the list.
=> Select first message in Illo/SN fixups

src/guiguts/html_convert.py
1. Output line number of snippet of text in error message to aid user in finding the problem
2. Raise exceptions throughout to give consistent error behavior
3. If an error occurs ask user if they want to load the pre-conversion backup file. If they do, load it but keep the current filename.
Fixes #687 
NTS: Merge after #686
=> Improve behavior if HTML autogen errors

src/guiguts/maintext.py, src/guiguts/search.py
This is a proof-of-concept for #564.
To try it out, do a search and you should see all matches highlighted in a subtle color, and the currently-active match in a more prominent color. You can go to the next match, etc, and the highlighted match will hop around but the inactive ones will all remain visible.
This is not production quality and has known bugs (for instance, the match highlights are not removed unless you start a new search, because I haven't gone through to find all the places they'd need to be cleaned up yet).
Is this on the track we were thinking? Any notes about the basic functionality before I go tidy up all the cobwebs?
One final note - the current match is also selected, as it has always been, but there's a more prominent highlight applied to the same range, so it's not …
=> Showing all matches during a search

src/guiguts/search.py
If user searches and quickly destroys search dialog, it can end up trying to write to the message label. Fixed by checking it exists first.
Fixes #690
=> Don't write to Search message if no dialog

src/guiguts/tools/bookloupe.py
Last line of table consisted of symbols, like `=`. These all get stripped before checking if the last character is a suitable punctuation character. Exception was caused by checking last character of an empty string.
Fixes #698
=> Fix bookloupe exception at end of table

src/guiguts/application.py, src/guiguts/maintext.py
This was already the case in maintext, but hadn't been adapted to work in the peer.
Fixes #692
=> Hide cursor in peer if text is selected

src/guiguts/file.py, src/guiguts/footnotes.py, src/guiguts/html_convert.py, src/guiguts/illo_sn_fixup.py, src/guiguts/maintext.py, src/guiguts/misc_tools.py, src/guiguts/search.py
After moving footnotes to LZ, code now checks if the FOOTNOTES heading has 4 blank lines before it.
If it does, then make sure it has at least 2 blank lines after it.
Testing note: if you manually edit LZ blank lines in order to test this, you should re-run the footnotes tool to ensure it knows all the locations correctly.
Fixes #691
(Also added a new method to return the range of the whole file, and used it everywhere it previously created a range from
`maintext().start()` to `maintext().end()`. Just a bit of code improvement :) )
=> Ensure FOOTNOTES heading has correct blank lines

src/guiguts/mainwindow.py
In checker dialogs such as bookloupe, use a regular arrow rather than the vertical bar insert cursor.
Fixes #702 - this makes sense for the reasons given in the issue.
Testing notes, move mouse over the list of bookloupe or WF messages.
=> Use normal mouse pointer arrow in checkers

src/guiguts/checkers.py, src/guiguts/search.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py
1. Instead of binding to dialog, bind to `top_frame` so that binding is only called once, instead of for every dialog child.
2. Rename `tidy_up` to the more explicit `on_destroy`.
3. CheckerDialog just overrides `on_destroy`, calling the super method.
4. Search overrides the existing `reset` method instead of using an explicit binding.
Fixes #683
=> Improve how code is executed on destroying dialog

src/guiguts/misc_tools.py
Example: `based on nature.“[A]`
Fixes #704
=> Report open curly quotes preceded by punctuation

src/guiguts/word_frequency.py
Fixes #720
Testing notes:
Run Tools->WF, then quit the program without closing the WF dialog first.
=> Fix exception if WF is up when program quits

src/guiguts/application.py, src/guiguts/misc_tools.py
1. In the HTML menu, Unmatched HTML tags reports on open tags that are not closed, or close tags that were not opened.
2. It does not attempt to check whether the HTML is valid, for example, putting an `h1` inside a `span`. The rules on what is valid are too complex, and the rules on what would make sense syntactically even more so. Use the HTML validator to check if HTML is valid.
3. It also does not have a list of all the valid HTML tags, so will report
`<mytag class="myclass">some text</yourtag>`
because `mytag` isn't closed.
But it won't report 
`<mytag class="myclass">some text</mytag>`
even though `mytag` is not a valid HTML tag.
Fixes #454
=> Add unmatched HTML tag check

src/guiguts/checkers.py, src/guiguts/footnotes.py, src/guiguts/html_tools.py, src/guiguts/illo_sn_fixup.py, src/guiguts/misc_tools.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/bookloupe.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/levenshtein.py, src/guiguts/tools/pptxt.py, src/guiguts/widgets.py
Each time some of the tools were re-run, a new tooltip object was created. So, although not visible (because all the tooltips appeared on top of each other) after
several re-runs, each time the cursor entered the list of messages, several tooltips were displayed.
Fixes #730
Testing notes:
Should be nothing noticeable. Check tooltips work in some checker dialogs, Find All, Spelling, WF, etc.
=> Don't create multiple tooltips

src/guiguts/maintext.py
If Search dialog was open when program was closed, it generated an exception trying to clear search highlights.
Fixes #735
=> Fix exception from Search when main window closed

src/guiguts/footnotes.py
Now that the FN dialog is not a plain CheckerDialog, it's necessary to get the correct mark prefix.
Fixes #737
=> Use correct mark name in FN dialog

README.md
@srjfoo discovered that Poetry 2 breaks with former behavior for `poetry shell`, which is now deprecated.
=> Update README to include Poetry 2.x information

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py
Two changes which are independent to improve the interplay between the text window prev/next page and the image viewer prev/next file.
For discussion as to whether either, neither or both of these are improvements:
1. When using prev/next image buttons in status bar (or equivalent buttons in Search-->Goto menu) step back/forward to the next page boundary, even if that means the insert cursor doesn't move. This happens if there are two or more page breaks at the same point in the file, due to full page illo or blank page.
2. Don't turn off Auto Image when prev/next file buttons are used in image viewer. Instead, just pause it until the user moves the mouse out of the image viewer. So the PPer can easily look back/forward a page or two around their current insert location, then when they …
=> Image viewer & next/prev page improvement

src/guiguts/html_convert.py
If the title (first bit of text in book) is marked up with `/*` or similar, then autogen surrounded it
with h1 and p markup.
Now, it just does h1.
=> Don't mark up title with h1 and p

src/guiguts/application.py, src/guiguts/html_tools.py
In HTML menu.
Reports similar things to GG1:
1. Broken internal links, where anchor for an href does not exist.
2. Broken file links, where href or src points to a file that does not exist (usually an image file)
3. Links that are "external", i.e. begin with "http"
4. Links that are empty, e.g. `href=""`
5. Similar to the above for CSS url function, e.g. `style="background-image: url("images/a1.jpg")`.
Note that there can be more than one url function in one style attribute value.
6. Files in the image folder that are nor referenced
7. Files in the image folder that have uppercase letters in the filename.
8. Reports a summary of statistics
9. Reports as INFO messages any anchors that are not referenced
Note: to see the last 2 in GG1, you have to check the verbose flag. Also note that the …
=> Add HTML Link Checker

src/guiguts/data/html/html_header.txt, src/guiguts/html_tools.py, src/guiguts/maintext.py
1. Remove `<p>` markup within caption
2. Remove `class=caption` from caption
3. Change HTML header file to make figcaption bold even without the `class=caption`
4. Remove superfluous trailing newline
5. Remove blank lines at start or end of caption
Fixes #736
=> Improve HTML Auto-illustration

src/guiguts/checkers.py, src/guiguts/footnotes.py, src/guiguts/maintext.py, src/guiguts/widgets.py
All dialogs can now get a unique prefix or any marks they create. Checker dialogs automatically remove
all such marks when reset/closed. Other dialog types need to remove their own marks.
Fixes #742 
Testing notes: Try a couple of checker dialogs, especially Footnotes, and especially move FNs to paragraphs. Should be no discernible change in behavior.
=> Move mark prefix getter into TopLevelDialog

src/guiguts/maintext.py
If peer was hidden when program started, and then gets shown later via Split Screen, it's theme wasn't updated.
=> Ensure peer column ruler gets correct theme

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/footnotes.py, src/guiguts/html_tools.py, src/guiguts/illo_sn_fixup.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/bookloupe.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/levenshtein.py, src/guiguts/tools/pptxt.py, src/guiguts/widgets.py
Re-organization of checker dialog creation to avoid re-creating widgets every time a tool is re-run
Fixes #755 
Testing notes: Do checker dialogs still work? Try Re-running the tool, closing dialog & re-opening from the menus, etc.
Any checker could be broken, but don't feel you need to check them all in great detail. The most at risk are footnotes, sidenote/illustration fixup and spell check.
=> Widget duplicates

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py, src/guiguts/widgets.py
When mouse enters/leaves the image viewer, change the border color. Should work correctly with themes. If you change theme, the border won't change immediately, but will as soon as you enter/leave the image viewer. We already tell the user that they may need to restart to get full effect of a theme change.
This is because if the user has AutoImg on, and they use the image viewer buttons to change the image, when the mouse leaves the image viewer, the image will flip back to the AutoImg image.
Fixes #759 as suggested by @tangledhelix
=> Highlight border of image viewer when focused

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/preferences.py, src/guiguts/root.py
Highlights proofer's notes in a visible but subtle way, to draw attention to them. Highlights in a rolling window as the viewport moves to avoid evaluating the entire file.
I chose what I thought were good colors for light & dark mode, but I'm open to feedback.
=> Highlight proofer notes

src/guiguts/tools/pptxt.py
1. Don't report ampersand in character checks because there's a better check later in "Ampersand character in line". Fixes #779 
2. Don't report asterisk in `       *       *       *       *       *` in character checks - it's a standard thought break. Fixes #778
=> Fix couple nits in PPtxt

src/guiguts/spell.py
When spell checking, every word is highlighted in blue in the dialog which some users find too much. If there was context with just the bad spelling in blue, this would be OK, but there isn't. So, don't highlight in blue.
Fixes #478
=> Don't highlight spellings in blue in dialog

src/guiguts/html_convert.py
Problem occurs if chapter heading has FN anchor.
Because only one anchor can be linked from a footnote, this should be the one in the chapter heading itself, not one in the Autogenerated ToC.
Fixes #775
=> Strip footnote anchors from auto ToC

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py, src/guiguts/widgets.py
Highlight HTML-style tags with color.
Note that the simple python HTML parser does fully detect invalid tags and/or may be confused by things that might also confuse a browser, e.g. unescaped `<`.
I have chosen a few common tags (a,p,span,div) to have their own color. All other valid tags get purple. All unrecognised tags are shown in red.
=> Add simple HTML syntax highlighting

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py
Adds two checkboxes to image viewer, to automatically fit the image to the viewport either by height or by width (of the viewport). The modes are mutually exclusive; only one may be active at a time. However, neither is required so they may both be inactive.
Operation is very simple: check the checkbox and the mode starts working; uncheck to turn off. If you check one and the other was checked, it will be automatically unchecked (they are mutually exclusive).
When either mode is turned on, the resize happens immediately. As image navigation happens, resize happens on load of the next/prev image.
If zooming an image manually, the manual zoom is kept until the viewer moves to a different image. If neither mode is active, the manual zoom level is left in place as you move from image to …
=> Add auto-fit-to-(height, width) in image viewer

src/guiguts/checkers.py, src/guiguts/footnotes.py, src/guiguts/html_tools.py, src/guiguts/illo_sn_fixup.py, src/guiguts/misc_tools.py, src/guiguts/search.py, src/guiguts/spell.py, src/guiguts/tools/bookloupe.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/levenshtein.py, src/guiguts/tools/pphtml.py, src/guiguts/tools/pptxt.py
There are either 2 or 6 buttons, depending on whether the checker is able to Fix a reported problem. The buttons should resize with the dialog width.
Each button has a tooltip, and clicking on each one is equivalent to using Ctrl/Cmd/Shift Left/Right mouse buttons in the message list, but just using a simple mouse click.
Fixes #752
I have decided for now not to add a Preference setting to control whether these buttons are shown.
=> Add buttons to checker dialogs

src/guiguts/application.py
HTML5 and CSS validators can be opened via options in the HTML menu. These are marked "(www)" to indicate that they will open a browser window. Also added "(www)" to a couple of Help menu options.
Fixes #451
=> Add link to PPWB

src/guiguts/application.py
Buttons that do something (e.g. a check) even if there is more that can be done, such as moving a sidenote, now do not get an ellipsis. It's reserved for tools that can't really do anything until the user types/clicks/etc in the dialog that appears.
Fixes #795
=> Remove some menu button ellipses

src/guiguts/html_tools.py
It was failing to accept the closing `]` when it wasn't at the end of the line (due to the `</p>`
Fixes #799
=> Fix Auto-illo bug when illo has trailing `</p>`

src/guiguts/mainwindow.py
Panning an image in Image Viewer using a mouse wheel or two-finger swipe on a trackpad or Magic Mouse (the `MouseWheel` Tk event) did not perform smoothly.
Mostly this is just a copy of the scroll handler code found in `ScrollableFrame.on_mouse_wheel()`.
Mac-specific.
=> Mac: Improve MouseWheel/trackpad for image panning

src/guiguts/file.py, src/guiguts/mainwindow.py
Bug-fix: when auto-fit modes are on, and the height or width of the viewer changes (whichever is relevant), the image was not redrawn until a new image was loaded.
Testing notes:
Using image viewer, either docked, or undocked, turn on an auto-fit mode and then resize the viewer. That can be one of:
- resize undocked window
- resize main window with docked viewer
- resize image viewer using the divider between it and the text pane(s)
It should dynamically resize to match the mode you've chosen (either by height or by width).
If the image changes (using either status-bar `<` `>` buttons or `Auto Image`) then it should also pop to the auto-fit size. If you manually zoom in/out it should remain as you zoomed it unless you either resize the window, or change to a different image.
If you …
=> Track image auto-fit with change in viewer size

src/guiguts/maintext.py
Convert Shift-click/drag in line number gutter to a shift/click/drag in the first column of the current text line, since that already does what we want.
=> Implement Shift-Click/Drag in line number gutter

src/guiguts/checkers.py, src/guiguts/misc_tools.py, src/guiguts/spell.py
Previously checking a message type meant that message type would be hidden, rather than enabled, which was not intuitive for new users. Now reversed, so all message types are checked initially, and user can Hide All, then turn back on just the one(s) they want to work on.
Also, generic FIx buttons hidden in Curly Quote Check since not really necessary. Not that Ctrl-clicking a message still does a "fix" operation. These operations are all available on existing buttons for those who prefer not to Ctrl-click.
Fixes #793
=> Swap meaning of Checker View Options (& minor curly quote checker change)

src/guiguts/mainwindow.py
Match line spacing in maintext since they are the same type of widget.
=> Increase Mac line spacing in checkers

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/preferences.py
In View Options dialog (from Bookloupe checker) add a checkbox to gray out any view options that are not relevant to the current set of messages, i.e. if no messages of that type are shown in the checker dialog.
Gray-ness should be updated live, i.e. if a user hides the last message of a given type, and the View Options dialog is visible, the view option for that type will be grayed out. And if the user re-runs the tool, causing a message of the type to appear in the list again, the view option should be ungrayed.
This is to support a common way of using View Options as described in #723
Fixes #723
=> Add "Gray out unused view options" button

src/guiguts/misc_dialogs.py, src/guiguts/widgets.py
Apply keyboard bindings to tabbed Notebook widget. Only example currently in code is Preferences dialog.
Already inbuilt were (Shift-)Ctrl-Tab to switch to prev/next. Added Cmd/Ctrl-digit, e.g. Ctrl-1 to change to first tab, to match behavior in other apps, e.g. browsers.
On Macs, added Command-Option-Left/Right to switch to prev/next to match behavior in browsers.
Fixes #822 
Testing notes: On macOS, Cmd-3 should change to the third tab, for example, and Cmd-Option-Left/Right should cycle round tabs.
=> Add keyboard bindings to change tabs

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/footnotes.py, src/guiguts/illo_sn_fixup.py, src/guiguts/maintext.py, src/guiguts/preferences.py, src/guiguts/root.py, src/guiguts/spell.py, src/guiguts/tools/jeebies.py, src/guiguts/tools/levenshtein.py, src/guiguts/utilities.py, src/guiguts/widgets.py, src/guiguts/word_frequency.py, tests/conftest.py
Several related to the case of variable names not following the established convention - case changed as needed. Some were "unused-argument" - underscore prepended to variable in line with convention, or argument removed.
=> Remove pylint warning suppression directives

src/guiguts/misc_tools.py
Bookloupe was an example of using View Options to
toggle show/hide based on error message text, whereas
this is an example of basing it on the error prefix.
First commit had checkbox for every message type.
Second (current) version just has two view options for double quotes (unconverted
ones and "other" message) and same for single quotes.
It's actually more helpful to have all double quote errors
(apart from unconverted) because otherwise if you look
to see why you got "Unexpected open double" it may
be because of an error earlier in the paragraph, but you
didn't notice because that error was hidden.
So, I think the second commit is the best split of View Options.
=> Quotes view options

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
Add advanced "Autofix RTL text" preference.
If this is False there is no change in behavior.
Defaults to False on Macs and True on Windows/Linux.
When a file is loaded, sections of Hebrew (ATM) are word-order reversed, i.e. order of chars within word is unchanged, just order of words changed.
When a file is saved, the same happens.
Also, and extra "Paste RTL text" menu option added for pasting in Hebrew from the forums.
=> RTL experiment

src/guiguts/application.py
Some keys for keyboard navigation were duplicated:
1. C & U were used twice in the Tools menu
2. S was used twice in the View menu
3. One entry in the RTL Text menu didn't have a key
=> Fix duplicate Alt keys

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
"Highlight Cursor Line" checkbox added to "Advanced" tab of Preferences dialog.
The cursor line highlighting is distracting to some users.
=> Make cursor line highlighting optional

src/guiguts/misc_tools.py, src/guiguts/widgets.py
In Stealth Scannos, ensure right hand end of path is displayed in combobox. Also that dropdown menu is
wide enough to show available paths. Also show a
tooltip with the full pathname.
Fixes #846
=> Display pathnames in combo boxes better

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/html_tools.py, src/guiguts/misc_dialogs.py, src/guiguts/spell.py, src/guiguts/tools/pphtml.py, src/guiguts/tools/pptxt.py
Fix erroneous "suspect" reports by PPtxt
PPtxt does not have suspect and non-suspect messages as some other tools do. The `(x5)` prefix showing that an asterisk occurred 5 times on the same line was
mistakenly being identified as a suspect flag.
Fixes #836
PPhtml: Detect ID attributes across line breaks
If `id="my_id"` is split across a line break, it wasn't detected by PPhtml, so might be reported as
`Target my_id not found.`
Use HTML parser instead of single line checks.
Note this error exists in other instances of pphtml.
Fixes #854
Output "Check complete" message in checkers
So that user knows check has run
Link HTML & CSS validators to man page
Manual page link was broken for these two tools.
Minor wording change to PPhtml message
Count of class="chapter" attributes now has quotes …
=> Fix several small bugs/annoyances

src/guiguts/tools/pphtml.py
When classname had hyphen in, it could get split into two classes.
Fixes #864
=> Fix PPhtml class bug

src/guiguts/application.py, src/guiguts/html_tools.py, src/guiguts/preferences.py
This PR has been tested against Mac and Linux (Ubuntu 24).
**Windows testing is needed!**
- Adds checkbox to Ebookmaker dialog to control debug output. By default `-v` is used (which will give INFO), with debug box checked, you also get DEBUG (`-v -v`).
- The path to ebookmaker is now expected to be a **directory** rather than a file. It should be the directory where the user ran `pipenv install` to install ebookmaker. **This is not backward-compatible** so users may need to change its value for ebookmaker to work again **even if it was working previously**.
- Since Ebookmaker's instructions for install are to use pipenv, my viewpoint is to follow that method and assume that's how the user installed it.
- Minor correction of a label, "Epub formats:" is now "Ebook formats:"
- Set …
=> Ebookmaker Mac/Linux support & other changes/improvements

src/guiguts/checkers.py, src/guiguts/html_tools.py, src/guiguts/tools/pptxt.py
1. Determine default severity better, and allow calling routine to specify severity when entry is added.
2. Warnings, errors or critical errors from ebookmaker will now have the severity in red at the start of the message.
3. If user chooses to sort by Alpha/Type, sort by severity, preserving message order within severities.
4. Add Suspects Only button.
5. Warn user if they need to select the ebookmaker dir, i.e. if the dialog field is empty.
=> Improve ebookmaker dialog

src/guiguts/maintext.py
Since we use the system-wide "selected text" highlight background to indicate the current line & column in the line numbers & column numbers margins, we need to also use the system-wide foreground, otherwise the text may be unreadable against the background.
=> Use correct fg col in line/column widgets

src/guiguts/maintext.py
Building on the previous work in #875, separate `CURSOR_LINE` highlight into `CURSOR_LINE_ACTIVE` and `_INACTIVE`. The highlights will be swapped between panes depending on which is currently active, rather than using "main" vs "peer" which in this project means essentially "top" vs "bottom" pane.
The "active" highlight is meant to be more prominent than the "inactive". In the case where the viewport is covering the same small area in both panes, the highlights will co-exist and their being different will help to differentiate which is which within each pane.
The "inactive" highlight is lower priority than the "active" so if they cover the same line, the active takes precedence. This means in the pathological case where the cursor is on the same line in both panes, both panes will appear …
=> Implement active/inactive pane cursorline

src/guiguts/preferences.py
Keep a "day" backup and a "week" backup. These
only get overwritten if they age past their time
period.
Fixes #882
Testing notes:
You may find variants on the following command useful if you do not want to wait for a week to test this:
`touch -m -t 04082015 GGprefs_day.json`
Also, one way to force a save of GGprefs is to load a different file, e.g. from the Recent files menu. Then you can edit the GGprefs file and the two backups and inspect which is the top file in the "recent_files" list. That way you can keep track of when one file is renamed to another.
=> Backup Prefs file

src/guiguts/application.py, src/guiguts/widgets.py
F1 now displays help for most recently focused dialog page, even if focus is in main window.
Fixes #888
=> Add Dialog Manual Page to Help menu

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py
`$u` is replaced with the 4 digit hex Unicode codepoint value of the current character shown in the status bar, or the empty string if none.
The following will look it up at unicodeplus.com and fileformat.info:
`https://www.unicodeplus.com/U+$u`
`https://www.fileformat.info/info/unicode/char/$u/index.htm`
=> Add `$u` to Custom Menu variables

src/guiguts/application.py, src/guiguts/html_tools.py, src/guiguts/preferences.py
In the HTML menu, pops a dialog which behaves
much like the Auto-Table controls in the GG1 HTML
Markup dialog.
1. Select a table that is formatted for text (with or without vertical lines)
2. Check whether table is one line per row, or it is "multiline" with blank lines separating rows.
3. Set default column alignments.
4. Specify column alignments not all the same, e.g. "LCR" will  make the first 3 columns left, center, right aligned, and any more cols will use the default.
5. Click the Convert button.
Fixes #449
=> Add HTML Auto-Table

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/misc_tools.py
Buttons delete the proofer comment highlighted by
the selected message, or all matching comments
and optionally hiding the message(s).
Also fixed minor errors in tooltips.
Fixes #866
=> Add buttons to Proofer Comment Checker

src/guiguts/mainwindow.py
If very small viewer scale was saved into Prefs, it could attempt to resize a subsequent image to smaller than 1 pixel, which was treated as zero.
Fixed by rounding up, and also ensuring image will be shown at least 50 pixels in width/height.
Fixes #899
Testing notes: Manually edit GGprefs.json & at about line 78 change `image_scale_factor` to something like 0.000001. Also ensure that fit to height/width are turned off, or they will override that scale. That should cause the crash in `master` but not this branch.
=> Fix image viewer crash

src/guiguts/mainwindow.py
Rather than let the user guess which image is being displayed, show it to them. The path leading up to the file, as well as the file extension, are stripped to create a short label (i.e. "001.png" becomes "001", and "washington.jpg" becomes "washington"). The label width adjusts dynamically to the label length.
When no image is loaded, the text `<no image>` is used as a placeholder.
Fixes #910
Testing notes:
Use image viewer as normal; the label should update to match what is displayed.
- When no image is loaded, the label should say `<no image>`
- The "short name" of the image is used as the label: no path, no file extension
- Should work as expected in Auto Image mode
- Should work if you mouse into the image viewer and navigate with the next/prev buttons
- Should update correctly if …
=> Add image short-name label to image viewer control strip

src/guiguts/ascii_tables.py
If table has a leading vertical line, i.e. left hand border, it is now possible to select it and move it to the right, then back to the left.
Fixes #918
=> Allow user to select leading vertical table line

src/guiguts/misc_tools.py
All operations need a call to undo_block_begin, even single operations, in order to separate them from
manual changes made by the user beforehand.
Fixes #920 
Testing notes: See linked issue. The following is a minimal file that will show the problem as described in the issue:
```
[Illustration: Fig[** .] 42.]
[Illustration: Fig[** .] 52.]
```
As noted in the issue, the key to breaking it is to manually correct the Fig 42 line by deleting the close bracket, then deleting the space, asterisks and open bracket, not by selecting the whole note and typing the correction.
=> Make proofer comment delete undo properly.

src/guiguts/word_frequency.py
Hyphen check didn't spot that "Rose Coloured" and
"rose-coloured" were suspects, even when the
"Ignore Case" checkbox was set.
Fixes #929
=> Make WF hyphen check respect "case" flag

src/guiguts/file.py
Fixes #908
Report via error message rather than allowing exception.
Testing notes:
On Windows, if another application had the text file open, GG could not rename it to ".bak", which caused an exception.
On other systems, you could probably simulate the kind of problems that might occur by disabling write access on the project directory: (`chmod -w proj_dir` ?)
=> Report save errors more gracefully

src/guiguts/tools/bookloupe.py
"Query word" and "Digit in" errors were being reported for things that were two words joined by an emdash. Split on emdash (in addition to existing splits on hyphen and space) in these circumstances.
Fixes #898 
Fixed #913
=> Bookloupe should split words at emdash

src/guiguts/ascii_tables.py
It was failing to highlight the current column on the first line of the table if that was line 1 of the file.
=> Highlight ASCII table correctly at top of file

src/guiguts/application.py, src/guiguts/misc_tools.py
Remove Unmatched-->Curly Quotes, and add its
ability to detect unmatched single quotes into the main Curly Quotes Check.
Also add a new View Options category, so the
user can hide the new single quote "errors" which
may be false positives due to apostrophes.
Fixes #903 
But not #671, which is being retained to consider the suggestion for an optional more aggressive single quote curlify strategy.
=> Rationalize curly quote checks

src/guiguts/word_frequency.py
1. Don't report `wife?’--the` in the emdash checks. It will report `wife--the` without the intervening punctuation, but with the other punctuation, it's not a potentially suspect use of emdash.
2. Report actual emdash characters in the emdash check in addition to double hyphens. This is different behavior to GG1.
Fixes #948 
Fixes #949 
Fixes #950
Example file for testing attached to issue #948
=> Small WF fixes

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/preferences.py
1. Allow multiple PersistentBoolean/Int/String variables to be linked to the same Prefkey, and still be updated correctly.
2. Don't create unnecessary PersistentBoolean when adding shadow commands for command palette.
=> Fix mutual exclusivity of image fit to height/width

src/guiguts/maintext.py
When a page break occurred at the END of a closing markup (like `L/`) the markup wasn't detected, unlike when the page break was at the beginning of the line.
Fixes #963 
Testing notes: test file in linked issue. Try wrapping the first 50 lines.
=> Fix block markup/page break rewrap bug

src/guiguts/tools/pphtml.py
Just output an info message that cover is landscape. Don't insist that the height is > 2560, as long as the width is, and vice versa for width.
Fixes #960
Testing notes: any HTML file, with a cover.jpg in the images folder. Then use an image program to resize the cover to various sizes, including portrait & landscape.
=> Don't complain about landscape covers

src/guiguts/file.py
This was mostly an artifact of re-using the page marker flags method of updating page positions. Not required and was annoying to users.
Fixes #961
Testing notes: Load a ppgen master file, e.g. the one from the linked issue. It should not show "edited" until a further edit is made.
=> Don't mark ppgen files as edited when loaded

src/guiguts/application.py, src/guiguts/html_tools.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/utilities.py, src/guiguts/widgets.py
Allow user to press key with modifiers instead of using checkboxes to set the modifiers.
Should also allow use of option key on macOS.
Should address points 6 & 7 of #956
=> Improve setting of shortcut keystrokes

src/guiguts/checkers.py
Previously on Macs only, focus remained in checker dialog when user clicked a message, whereas on
other platforms, focus switched to main text.
This commit makes all platforms behave like Mac.
Fixes #966
=> Don't switch focus to maintext from checkers

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py, src/guiguts/root.py
Since the change to store menus differently so they can be created with new shortcuts, it's no longer
necessary to pass in a PersistentBoolean - just the Prefkey is sufficient. So several of these variables are no longer needed.
Things that might have broken:
Full Screen (already tested on Windows)
Show/Hide internal image viewer
Auto Image
Invert Image
Split Text Window
Highlight Proofer comment
Highlight quote/bracket
Show full character name in status bar
Highlight alignment column
=> Remove unnecessary PersistentBool variables

src/guiguts/file.py, src/guiguts/footnotes.py
Fixes #964
Testing notes: Example file in linked issue. In master after using Tidy Footnotes in the FN dialog, the footnote is not rewrapped, and has a short line.
=> Wrap footnotes when tidying them

src/guiguts/application.py, src/guiguts/widgets.py
Use alternative internal name `.menu` if `.f.l` fails.
=> Fix Tk9 Comboboxes

src/guiguts/file.py
Setting a bookmark didn't mark the file as edited; therefore you could close or quit the file without saving (or being asked if you want to save) and lose the bookmark permanently.
Testing notes:
- On `master`, set a bookmark and then close or quit without saving. The bookmark should be lost on next startup.
- On this branch, set a bookmark and then close or quit without saving; you should be asked if you want to save.
Fixes #989
=> Mark file state dirty when setting bookmark

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
Some regexes can take effectively for ever, so add a timeout, settable via an advanced Pref.
If regex times out during search, disable highlighting of search string temporarily, or it will keep trying to repeat the failing search.
Error message may appear twice, once for the search and once for the highlighting. I think this is an
acceptable price to pay - alternatives such as setting a flag telling searches to be ignored would run a
risk of breaking things. This is to fix a very rare occurrence in a way that doesn't risk breaking
other user searches or intra-code searching.
=> Add regex timeout

src/guiguts/file.py, src/guiguts/mainwindow.py
Adds a button to the image viewer control frame to rotate the image by 90º counter-clockwise. If an image has been rotated, the rotation will be stored in the JSON file to persist across restarts. Images that haven't been rotated aren't stored in this data and assumed to be rotated 0º.
Testing notes:
- Load a project with images
- Rotate some images however you like
- Navigate away and back again; the rotation should be remembered
- Save the file and restart; the rotations should be remembered
- Rotate more images, without saving, and try to close the file. It should ask you to save.
There's a new key in the JSON file called `imagerotate` that stores the data. By default, images aren't in this data. Once an image has been rotated, it gets added and tracked.
Fixes #953
=> Image rotation

src/guiguts/maintext.py
If user tries to extend column selection using
Shift+Alt+click & drag (Shift+Cmd[**Option] on Mac) as the
first action after starting the program, the `tk::anchor1` mark was unset, causing an exception.
Doesn't make sense for user to do that, but we don't want exceptions.
Fixes #982 
Testing notes:
Contrary to initial report in #982, it's not plain column select, but Shift+column select that causes the exception.
=> Fix column select exception

src/guiguts/application.py, src/guiguts/misc_tools.py
The reason for not calling it "Indent Selection" as in GG1, is that if you don't have a selection, it just indents the current line, which seems like it might be useful.
Fixes #946
=> Add Indent +1, +4 and -1 space to Text menu

README.md, poetry.lock, pyproject.toml, src/guiguts/ascii_tables.py, src/guiguts/html_tools.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/tools/levenshtein.py, src/guiguts/tools/pphtml.py, src/guiguts/utilities.py
Update various checking tools to more recent versions, and fix issues reported by them in the code.
Once merged, this should allow devs to use python
3.11, 3.12 or 3.13 without flake and its cronies whining.
Fixes #1002
Testing notes - will need `poetry install` and a quick check things still seem to work OK (i.e. don't crash), including rewrapping Word Distance Check. This should only affect devs, not users, so shouldn't matter whether you are using Python 3.11 or 3.13 to test.
=> Updates relating to python 3.13

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/widgets.py
It's really the Unicode Block dialog, but with the dropdown block selection set to Commonly Used
Chars.
If you change blocks, it will be stored in the pref, and when you next do Unicode Block, it will show
that block, but if you do Common Chars, it will
force to that. If you change the block to be
Common Chars, that will be stored in the pref,
and that's what you'll get next time you do pop
Unicode Block.
Also added Shift left/right click to status bar, where the character name is shown - instructions in tooltip.
Fixes #975
=> Add Commonly Used Chars to Unicode menu

src/guiguts/application.py, src/guiguts/data/scannos/regex.json, src/guiguts/misc_tools.py
1. Five scannos with hints "Find a string that starts with xx and change it to yy" are better with a lookahead to check there is a character after it. This stops them matching "tb" (thought break) or "hr" (horizontal rule).
2. Scannos dialog tooltip now includes "Shift" actions
3. Various "Stealth Scannos" shadow commands added, including Replace, Replace All, Prev Scanno, Next Scanno.
4. "guess" exception extended to  include "(mar)quess"
5. Punct at start of line no longer triggered by ellipsis
6. "ii" now only suspected "ll" if preceded by a, e, o, u.
7. Ellipsis followed by lower case no longer reported
=> Improvements to Stealth Scannos

src/guiguts/misc_dialogs.py
1. Show large version of character (like proofing interface character picker)
2. Show name of character in dialog
3. Remove tooltips
4. Also, fix bug when popping unicode block using the unicode search dialog. If the dialog already existed, it remained showing the current block instead of the new one requested by unicode search.
=> Display unicode char name in dialog not tooltip

src/guiguts/tools/bookloupe.py
1. Ignore `*.png` and `*.jpg` in the "Digit in..." check.
2. Change "round brackets" to "parentheses"
Not planning to do the multi-paragraph square bracket request in #843
=> Fix Bookloupe gripes

src/guiguts/maintext.py, src/guiguts/misc_dialogs.py
On Windows/Linux, Alt+Key can open a menu, so if
there is a menu which has that as a shortcut, then warn in the same way as the other warning about
re-using shortcuts.
Fixes #1014
=> Trap attempt to use Alt+Key as shortcut

src/guiguts/word_frequency.py
1. Permit "Joseph-Marie" as mixed case, i.e. as long as each part of a word is cased correctly. Fixes #897 
2. Improve searching when clicking on words, for example `*--the` reported by emdash check. Fixes #1022
=> Fix minor WF bugs

src/guiguts/application.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py
Fixes #1026
The order is main text, peer window (if visible), status bar, image viewer (if visible and docked), back to main text. If image viewer is floating, it is not included in the tab loop from the main window, but has its own tab loop. You need to Ctrl/Cmd+tab or click in the image viewer to get focus in the window, then tabbing will just cycle through the image viewer buttons. In short, the floating image viewer should behave like a dialog as far as tabbing is concerned.
Testing notes - there are 6 cases to test:
1. No split text or image viewer
2. Just split text
3. Just docked image viewer
4. Just undocked image viewer
5. Split text and docked image viewer 6 Split text and undocked image viewer
Transition between regions is the most likely place for things to go wrong, e.g. at …
=> Fix tabbing through statusbar/image viewer

src/guiguts/mainwindow.py
Testing notes:
In Tk8, you should see a debug print "Failed to bind TouchpadScroll". It would be interesting to know if Tk9 gives the same message.
In Tk8 and Tk9, attempt to scroll the minimum amount in the image viewer, using the mousewheel.
You should see a debug print `delta: <nn>` in the shell window. When I scroll the mouse wheel one notch, I get a delta of +/- 120.
In Tk8, I think you should get a delta of +/- 1.
It would be interesting to know what Tk9 gives.
It's possible that using touchpad scrolling will give lots of messages `Touchpad: <nn>`. Again, it would be interesting to know what happens there. I wouldn't expect the touchpad to do any scrolling, just output debug messages at the moment.
=> Investigate tk9 Mac scroll

src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/page_details.py, src/guiguts/search.py, src/guiguts/widgets.py
1. Home (Cmd+Up) to go to top
2. End (Cmd+Down) to go to bottom
3. Return to "execute" (where appropriate)
4. Shift/Ctrl/Return for alternative execution
5. Tooltips describe possibilities for each Treeview
Treeviews affected:
Custom Menu, Customize dialog;
Page Details (Shift-click Lbl in status bar)
Tools Unicode Search dialog
Command Palette
Help Compose Key Sequences
Fixes #1020
=> Make Treeview keyboard navigation consistent

src/guiguts/word_frequency.py
Word Frequency now ignores lines that begin with
`.bn ` (bin file command)
`.pn ` (page number command)
`//` (comment)
Fixes #1030
=> Make WF ignore certain ppgen source lines

src/guiguts/misc_dialogs.py
When editing a command from command palette, allow tab and Shift+tab to perform default focus switching behavior.
Also don't accept other combinations, e.g. Ctrl+tab, if user somehow manages to get them into the
shortcut box.
=> Make tab perform default action in Edit Command

src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py
See all the "Image" shadows by typing "Image" into Command Palette.
This adds zoom in/out (Ctrl/Cmd-plus/minus) and
fit to height (but not autofit) (Ctrl/Cmd-zero).
Those were the default shortcuts we already had, but this adds them as shadow commands, so the user can reassign them.
Test in docked and undocked state, and when image
is not shown.
=> Add shadow commands for image zoom

src/guiguts/application.py, src/guiguts/misc_dialogs.py, src/guiguts/widgets.py
Bind "Shift+Return" to "Apply" button in an
Ok, Apply, Cancel dialog, in the same way as "Return" activates the "OK" button, and "Escape" activates
the "Cancel" button.
Also, add "Apply" in Surround Selection With" as a shadow command, so it can be activated when the
dialog doesn't have focus (because user has just
selected the text they want to surround).
This latter bit fixes #1007
=> Improve keyboard support for "Apply"

src/guiguts/misc_dialogs.py, src/guiguts/page_details.py, src/guiguts/widgets.py
Switch to space to activate some Treeviews
In Page Labels, use Space instead of Return.
In Unicode Search allow Space or Return.
Only enable Apply/OK in Page Labels when needed
=> Alternative apply

src/guiguts/ascii_tables.py, src/guiguts/checkers.py, src/guiguts/footnotes.py, src/guiguts/misc_dialogs.py, src/guiguts/misc_tools.py, src/guiguts/widgets.py
When Page Sep dialog is being used, the Undo/Redo
buttons in the dialog (and dialog shortcuts) not only
performed undo/redo, but also refreshed the display
to show the current page separator. However, using
Undo/Redo from the main Edit menu, or Ctrl-Z, etc.
when focused in maintext did not do the refresh.
This commit fixes that, so that however the Undo is
activated, the Refresh will happen. Once the dialog is
closed, the additional refresh will no longer occur.
Fixes [#938](https://github.com/DistributedProofreaders/guiguts-py/issues/938)
=> Make main text menu Undo/Ctrl-Z refresh current separator in the Page Separator Fixup dialog

src/guiguts/application.py, src/guiguts/preferences.py, src/guiguts/word_frequency.py
In master, "Two Words" is always on, so "flash light" will be queried as a possible suspect with "flash-light".
This commit makes that optional, with a checkbox next to the Hyphens radiobutton in WF. This is similar to GG1, except there it is in the Prefs menu, not the WF dialog.
(Note "flashlight" as one word is always queried against "flash-light", and is unchanged by this commit.)
Fixes #925
=> Add "Two Words" as option in WF Hyphens

poetry.lock, src/guiguts/tools/pptxt.py
Fixes #761 (see issue for example files)
1. Suppress multiple identical repeated word errors - if a line contains a word several times, e.g. in a table heading, we only want one report per line if the same word is repeated in each column heading
2. Catch repeated word at line start with spaces - Repeated words are reported if the first is at the end of a line, and the second is at the start of the next line. However, the regex didn't allow the second word to have spaces before it, which it might for indented piece of text, e.g. blockquote.
3. Fix repeated words bug - A line with two distinct repeats, e.g.
`dog dog cat dog dog`
was reported as having 3 repeats, due to a bug in the way the first word in each double match was cleared to avoid re-finding it.
4. Don't report spaced close curly …
=> PPtxt improvements

src/guiguts/illo_sn_fixup.py
When checking to see if the illo was mid-paragraph, it didn't take account of the fact that there might be `[**...]` within the illo markup, so interpreted the `]` as closing the illo markup.
Fixes #1044
=> Fix "`[**...]` inside illo markup" bug

src/guiguts/application.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py
Previously if a closing curly quote was missing at the end of a paragraph, no error was output if there was an open quote at the start of the next paragraph. This was to avoid many false positives from this common occurrence. This feature is in PPWB's ppsmq, and in GG1.
However, it's not possible to know that the missing quote was missing at the END of the paragraph, e.g. `"Hello, he said.` So, this exception could cause
true errors to be omitted.
This commit makes the exception optional via a
Preference controlled by a checkbox in the Curly
Quote Check dialog.
Fixes #1052
=> Make curly quote exception optional

src/guiguts/tools/pphtml.py
Just output a warning for a large cover, not an error, since there is no actual file size limit specified in the PPFAQ.
Fixes #1050
=> Downgrade error for cover > 1MB

src/guiguts/tools/bookloupe.py
For example, `water.” she said`
The quotes after the period blocked the test from
detecting the following lowercase `s`. Now fixed in Bookloupe.
Fixes #951
=> Trap lowercase after period with quotes

src/guiguts/misc_tools.py, src/guiguts/search.py
Because manual page names have changed
Fixes pressing F1 (or Help->Dialog Manual Page) for the S/R dialog, Proofer Comments, and Asterisk Check, all of which are in the Search Menu
Fixes #1063
=> Correct a few help links

src/guiguts/application.py, src/guiguts/misc_tools.py
1. Center current or selected lines
2. Right-align current or selected lines
3. Right align numbers in current or selected lines, e.g. in ToC
`   Chapter 1   46`
`   Chapter 2   47-50`
The bit that gets right-aligned comes after at least a
double space and consists only of digits, hyphen or
en-dash.
Fixes #1061
=> Add text alignment options

src/guiguts/application.py, src/guiguts/misc_tools.py
Pops S/R dialog, just like GG1, and sets checkboxes and strings in Search/Replace fields to prepare it for use.
Fixes #658
=> Add "Convert `<sc>` manually"

src/guiguts/maintext.py
Adjusts scroll speeds and scrolls by pixels rather than by units, to scroll more smoothly during select-drag.
Testing notes:
- drag to scroll and observe speed/jerkiness/etc on `master`
- then repeat on this branch
- types of scrolling:
- drag-select vertical (either direction)
- drag-select horizontal (either direction)
- column-drag-select vertical (either direction)
- column-drag-select horizontal (either direction)
For me these values seem to work and feel good. I'm happy to hear opinions about how to further tune the min/max speed, or how many pixels to scroll per iteration. For me, using 1 pixel seemed too fast, but others might have a different experience.
Fixes #1094
=> Smoother select-scrolling by using pixels

src/guiguts/mainwindow.py
Broken for Mac users in #1005 by comparing Tk version to 3.7 instead of 8.7!
Testing notes: this won't make it any smoother than before, nor fix any other problems, but should revert to the "basically works" situation pre-#1005. Apologies for the typo!
=> Fix mousewheel scrolling in image

src/guiguts/tools/pphtml.py, tests/expected/pphtml1.txt
Wait until we've passed the `</style>` line before checking for double hyphens.
Note:
This minor edit caused one of the new tests to "fail" - not actually an error, but the test detected that the warning about double hyphens was no longer in one of the pphtml output test files.
=> Don't report `/*-------*/` in CSS style section

src/guiguts/mainwindow.py
If no filename, button did nothing. Now just opens a load dialog without specifying an initial directory, so should either open in a default place or the previous dir used in a similar dialog - will depend on OS behavior.
Fixes #1102
=> Fix image viewer browse/load button

src/guiguts/mainwindow.py
Improve image pane scrolling speed and responsiveness when using the trackpad or mouse wheel.
On Linux, ignore this event. It causes the UI to seize up, even if only temporarily, and even after releasing, the image still doesn't scroll.
Testing notes:
- First try scrolling the image pane with trackpad and/or mousewheel on `master` to get a baseline
- Then try again on this branch; it will hopefully be fairly smooth
- Should work to scroll both horizontally and vertically.
I refactored the routine, but it turned out that a major key was to not call `show_image()`. It appears to be unnecessary and was probably the source of most of the slowness.
=> Update scrollwheel/trackpad scroll in image pane

src/guiguts/widgets.py
Horizontal scroll bindings weren't being removed when the mouse leaves the ScrollableFrame.
=> Fix horizontal scroll bug

src/guiguts/html_convert.py
During HTML generation, if a pagenum is inside a paragraph, it doesn't have `<p>` markup added round it. However if it is within poetry, the markup was still being added. This commit stops that happening.
Fixes #1108
=> Don't surround poetry pagenum with `<p>` markup

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/maintext.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/widgets.py, tests/test_internals.py
1. Current line in checker list of messages
2. Highlighted word in message, e.g. "he" in Jeebies message
3. Error prefix, e.g. type of error in Curly Quote Check
Doesn't let you configure bg or fg of a color if it would have no effect, e.g. error prefix is fg only, and main window selected color when window not focused (inactive) is bg only.
Also miscellaneous code re-org, some of which was needed, and some just to improve it.
Fixes #1111
=> Make checker dialog colors configurable

src/guiguts/search.py
When using `\C...\E` can now use the following 2 functions:
1. cset("key", value) - stores (and returns) the given value using the key string (must be in quotes)
2. cget("key") - returns the previously-stored value
Note Python syntax
`<value if true> if <test> else <value if false>`
Warning: you can execute dangerous stuff if you want to, e.g. `\C exit() \E` will exit the program. How to reformat your hard disk is left as an exercise for the reader.
=> Add regex ability to store persistent variables

src/guiguts/search.py
If there are side effects from the replacement, e.g. storing something in a persistent variable, then the previous internal behavior of making the replacements in reverse order would give unexpected results.
=> Make Replace All search forward

src/guiguts/application.py, src/guiguts/mainwindow.py, src/guiguts/misc_dialogs.py, src/guiguts/preferences.py
In Preferences, Image Viewer tab, can switch between left and right. In order to give visual feedback, If user changes the setting, the viewer is displayed docked on the side they chose, even if it was previously
floating or hidden.
Fixes #484
=> Allow image viewer to be docked on left or right

src/guiguts/application.py
On at least Mac and Linux (I'm not sure about Windows), `--version` is a commonly expected argument. This PR adds it.
Testing notes:
- Run `guiguts --version`.
- The version number should print to the console.
- That's it, then the program should exit and return you to a prompt.
=> Add --version flag to show version at CLI

src/guiguts/illo_sn_fixup.py
If two illos are adjacent (one blank line between) and the upper one has blank lines, i.e. multi paragraph, and the user tries to move the lower one upwards, it is supposed to do nothing because you can't move illos past one another, but if finds the blank line in the upper illo and tries to move it in there, potentially losing lines in the process.
This fix makes it detect the end of illo markup, then it tracks back to find the start of illo markup, before beginning the search process. If indeed it was an illo, it will do nothing, but if it was a sidenote, it can move the illo above the sidenote.
Hopefully fixes #1143
=> Fix Illo Fixup move bug

CHANGELOG.md, src/guiguts/html_convert.py
If file begins with `/#` then HTML generation fails because the `/#` ends up on a line with other markup. Then later, this open markup is not recognized, and a fatal error occurs when the matching close markup is found.
This is a quick fix to let HTML generation continue, rather than causing a fatal error.
#1157 addresses the issue more fully.
=> Don't break leading `/#` markup in HTML gen

src/guiguts/application.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py, src/guiguts/search.py
User can now change the number of replace fields shown in the SR dialog between 2 and 10, default is 3.
Dialog should resize correctly, and setting is stored in prefs, so should be persistent.
Also fixed minor bug relating to multi-replace. In master, if a replacement string is used in replace field 1, for example, it doesn't appear in the drop down for replace field 2 until the dialog is closed and re-opened. With this commit, strings are added to drop-down history for all fields as soon as they are used in any field.
Fixes #792
=> Add variable multi-replace to SR dialog

src/guiguts/word_frequency.py
Missing comma led to strings being concatenated, rather than joined with newline between
=> Fix WF tooltip

src/guiguts/checkers.py, src/guiguts/misc_tools.py
Programmer can now choose what "matching" means for each tool:
1. Message must match exactly, e.g. Jeebies, etc
2. Highlighted portion must match, e.g. Proofer Comments
3. Error prefix (red) must match, e.g. Basic Fixup
4. All messages match, e.g. Stealth Scannos
Tooltips should also be appropriate to the type of match.
Fixes #1167
=> Make checker dialog matching more flexible

src/guiguts/footnotes.py
A nested square bracket within a continued footnote can cause Footnote Fixup to combine two footnotes into one.
This is a simple fix to report this situation by detecting that and unexpected `[Footnote` appears within the text of a footnote.
A more robust search method or fix may transpire when the work is done for #515, but this will at least alert PPers. This is quite a rare event, but if it happens, the PPer can either copy/paste the continuation text into the correct place, or close the nested square bracket temporarily until footnote fixup is complete.
Fixes #1155
=> Warn if nested bracket confuses Footnote Fixup

src/guiguts/application.py, src/guiguts/checkers.py
1. Up/down arrow buttons select prev/next message in any checker dialog (not WF)
2. Shadow commands added for up/down and fix/hide/etc buttons
3. Shadow command works for the checker dialog that currently has keyboard focus. Note that this means you can't use it directly from the Command Palette (because then the Command Palette has focus), so you have to set up a keyboard shortcut.
3. Keyboard shortcut should do the same as clicking the relevant button.
4. If you use a shortcut for a button that does not exist in that dialog, e.g. Spell Check doesn't have Fix buttons, then nothing should happen.
Fixes #1080
=> Add up/down buttons to checker dialogs

src/guiguts/tools/levenshtein.py
Instead of separating entries with blank line, which gets overshadowed by the 4-hyphen separator within an entry, separate entries with line of equal signs
=> Separate Word Distance entries more visibly

src/guiguts/tools/pptxt.py, tests/expected/pptxt1.txt
If all quotes are straight this is reported near the top of the pptxt output. If that happens, then it's not necessary to also report straight quotes in the "Character Checks" section later, since they are expected characters, not unusual/surprising ones
Fixes #1130
=> Don't report pptxt straight quotes if all straight

src/guiguts/html_tools.py
Since the PPer wouldn't/shouldn't be removing these, even if they are unused, i.e. not linked to within the file, the HTML Link Checker shouldn't report them, since they mask true positives.
Fixes #1136
=> Don't report "Page_nn" ids as unused anchors

src/guiguts/misc_tools.py
This may be temporary, depending on what is done for issue #1175, but it makes sense for Prev/Next to be adjacent, or user has to move mouse back & forth across the dialog.
Fixes #1079
=> Reorganize Stealth Scanno buttons

src/guiguts/misc_dialogs.py, src/guiguts/widgets.py
Shadow command for Surround Selection did nothing if the dialog had been dismissed. In fact, it could work perfectly well without the dialog, using the most recent before/after text (like Find Next for S/R dialog).
This may have broken shadow commands generally, since it required some under-the-hood changes to make this type of shadow command work without the dialog. It means it will be easy to do similar shadow commands in future.
Things to try: the new Checker dialog commands, like "Hide"; Scanno Checker commands, like "Next Scanno". These do require the dialog to be visible, but should work the same as they do in master.
=> Make Surround Selection Apply work without dialog

src/guiguts/word_frequency.py
Simple keystrokes navigate the WF list, e.g. "x" goes to the first word beginning with "x".
It was also trapping combinations like "Alt-d" and "Cmd-s". Allow these to pass through for default handling.
Fixes #1184
Testing notes:
1. Edit the main text so that file is modifed and needs saving.
2. Run WF - all words, and see how key strokes navigate up & down the list.
3. With focus still in WF, press Cmd+s to save file
=> Don't trap GG shortcut sequences in WF

src/guiguts/word_frequency.py
Remove "Ligatures" from the "Diacritics/Ligatures" label due to confusion with the "Ligatures" label. 
Instead use "Diacritics/æ/œ"
=> Change WF Diacritics label

src/guiguts/footnotes.py
Previously Alpha/Type sorting put all the anchors first, then the footnotes, and sorted within those categories by row.col
Now, put footnotes before anchors,; put those with errors before those without; sort error types alphabetically; sort within types by rowcol
Fixes #1200
=> Improve footnote sorting

src/guiguts/application.py
To reduce differences across platforms.
"Settings" is an acceptable name for Windows, and is the standard word for macOS.
=> Change menu button from Preferences to Settings

src/guiguts/application.py
Add "Settings" to end of Edit menu, and "Quit" to
end of File menu on Macs.
On Windows/Linux, "Preferences" was changed to
"Settings" by #1205. This PR changes "Exit" to "Quit"
=> Add buttons for cross-platform consistency

src/guiguts/application.py, src/guiguts/misc_dialogs.py, src/guiguts/misc_tools.py, src/guiguts/preferences.py
Add a preference to the Settings, Advanced Tab, for single quote conversion to be "strict" (i.e like `master`) or not.
If not, and a single quote is found within double quotes in the same paragraph, and the single quote as at the start of a word, it is assumed to be an apostrophe and converted to a curly one.
Fixes #671
=> Add less strict curly quote conversion

src/guiguts/misc_tools.py
"DQ not converted" is now included in "Other double quote errors, and similarly for single quotes.
Fixes #1215
=> Fix Curly Quote View Options

src/guiguts/maintext.py
Will never affect most people. Note that warnings are output in the command window and the message log.
There will not be a popup window.
Fixes #1229
=> Output warning if non-utf8 file loaded

src/guiguts/html_convert.py
Fixes #1206 
Stops footnote anchor wrapping separately from the word preceding it.
=> Add Word Joiner before HTML footnote anchors

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py
When user sets bookmark, if there is a selection, also mark and save that.
When user restores such a bookmark, the selection will also be restored.
Also, highlighting of bookmarks (brief flash of green) was broken in master, so fixed as well.
Also, ensure focus is in main text after using the "restore selection" button in the toolbar
Fixes #1225
=> Extend bookmarks to also save current selection

src/guiguts/footnotes.py
If a footnote has a footnote, with the anchor on the first line of the original footnote, then re-indexing causes marks to be moved, and the whole first line of the footnote is replaced with an anchor.
Fixed by only replacing the footnote label when the reindexing is done.
Fixes #1238
=> Fix reindex bug if footnote has 1st line footnote

src/guiguts/search.py
When dialog closes remove the highlights because these highlights are linked to the S/R dialog Highlight All button.
Fixes #1252
=> Remove "Highlight All" highlights when close S/R

src/guiguts/maintext.py
These are used for checkers, WF, Help About and Message Log.
Fixes #1260
=> Add sizegrip to ScrolledReadonlyTexts

src/guiguts/html_convert.py
Extend exception from DP markup to any HTML tag, to allow PPers to use HTML markup to flag corrections, for example, before they do HTML gen.
=> Don't convert `<`,`>` in HTML markup HTML gen

src/guiguts/mainwindow.py
Make it possible to run a command without `start`, and display the results in a console.
Only affects Windows
The former command 
`start cmd.exe /k python.exe C:/DP/ppgen-develop/ppgen.py -i $f -img`
can now be run as
`cmd.exe /k python.exe C:/DP/ppgen-develop/ppgen.py -i $f -img`
=> Adjust Windows subprocess runs

README.md
Explicitly mention that commands should be typed in a command window.
Fixes #1282
=> Clarify Windows/Mac installation instructions

src/guiguts/html_convert.py
When inside the HTML markup for index or list, which is `<ul>` or `<ol>`, paragraphs are not allowed, so the pagenum should be a bare span, not wrapped in `<p>`
Fixes #1278
=> Don't add `<p>` markup to pagenums in index/list

src/guiguts/maintext.py
Since the menu option is part of the main window, using the menu forces focus back to the main text, unless you either use a keyboard shortcut, or tear-off menu.
Fixes #1293
=> Paste Hebrew into the widget with focus

src/guiguts/html_convert.py
When sidenote was all on one line, the end point of the sidenote was moved by the conversion of the start of the sidenote. Fixed by converting end first, then start.
=> Fix bug in converting one-line sidenotes

src/guiguts/maintext.py
Problem caused by Tcl/Tk interpreting mark name with a hyphen as having a mal-formed subtraction to the base index location, e.g. `a-1` gave mark `Pga-1`, and if this is offset, you got `Pga-1-3c` which is illegal.
Fixes #1292
=> Stop exception from png names containing hyphens

src/guiguts/tools/pphtml.py
It was finding the first occurrence of the class name as a word, e.g. "right", which could occur in other places. Changed to search for ".right" instead
Fixes #1296
=> Report correct location of unused CSS

src/guiguts/tools/pphtml.py
It can be perfectly valid for several links to point to the same ID, so should be a warning (for PPer to check they haven't mis-linked in the ToC, for example) rather than an error.
Fixes #1301
=> Report WARN not FAIL in PPhtml for multiple links

src/guiguts/html_convert.py, tests/expected/htmlconvert1.txt, tests/expected/htmlconvert2.txt
Remove/preserve block markup surrounding the book
title as appropriate.
1. If block markup only surrounds title, remove it.
2. If title at start of block markup, move it up outside the block markup
3. If title at end of block markup, move if down outside the block markup
4. If title in middle of block markup, just let it add h1 markup inside the HTML that the block markup generates. May be incorrect HTML if markup and title are giving autogenerate contradictory instructions
Also, add chapter div around block markup that has 4 or more blank lines before it, e.g. verso page.
Fixes #1307
=> Improve HTML autogeneration

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/preferences.py, src/guiguts/word_frequency.py
Typing a single key searched for the first occurrence of a
word beginning with the letter. Extend this to checker
dialogs. Also, if multiple keys typed less than 1 second apart,
search for message beginning with whole string, like an
incremental search.
Since checkers often contain longer messages than WF,
e.g. context of error, as well as headings, add a "Full search"
option (next to up/down arrows) that searches whole of
message text (not row/col, nor red error type) rather than
only matching at the start of the text.
Example: running pptxt, type "ellipsis" to jump to section
describing ellipsis checks.
=> Add keystroke character search to WF & checkers

src/guiguts/maintext.py
Initial commit to gather feedback...
1. Only drags the first bit of a column selection - one possibility instead would be to disable dragging if there's a column selection
2. If you drag below the bottom of the screen, it still works, but appears to select all the intervening text until you release the mouse, when the dragged text should appear in the correct place. Again, may be possible to fix.
3. Dropping should drop immediately before the character the mouse is released over, unless at the very right of that character, in which case it should go to the right.
Testing:
Drag small bits of text left and right, as well as larger chunks up or down.
=> Allow user to drag selected text to another place

src/guiguts/application.py
When the file name changes, previously the whole menu system was cleared and re-written, just because the Recent Documents menu needed rewriting. Either the repeated clearing and recreating (internal structures or Tk menus) or occasional timing clashes of using the menu and recreating it at the same time caused GG to silently exit.
Fixed by rewriting the labels and commands in the Recent Docs menu and not deleting/recreating everything.
Fixes #1319
=> Fix silent crash using Recent Files menu

src/guiguts/maintext.py
If the user ignored the red regex warning and searches anyway, the search match highlighting code raised an exception.
Treat like the regex timeout situation - output a single error and turn off match highlights until the user does another search.
Fixes #1318
=> Fix exception caused by searching for bad regex

src/guiguts/application.py, src/guiguts/checkers.py, src/guiguts/mainwindow.py, src/guiguts/search.py
1. Show last message in box
2. Fade message after 5 seconds
3. If message box doesn't fit on same line as buttons, drop it (and the "Working" label) to a second line.
4. Take into account whether ordinal button is displaying name or not, i.e. allow more space for it if it is.
5. When the user resizes the main window or changes the ordinal names preference, recalculate whether 1 or 2 lines are required in the status bar.
=> Provide message box in status bar

src/guiguts/search.py
`\N` is the opposite to `\R`, i.e. it converts a number written in Roman numerals to Arabic. Number can be upper or lower case, but must be a valid Roman number or an error will be reported.
Fixes #1270
=> Add `\N` to extended regex codes

src/guiguts/maintext.py
If user clicks on selection, don't go into full dragging mode unless they actually move the mouse.
1. Don't change cursor to drag cursor unless mouse has moved
2. When mouse is released over the selected text, treat it like a click, i.e. position insert cursor and clear selection.
Fixes #1333
=> Fix click-on-selection bug

src/guiguts/footnotes.py
Continuation footnotes are already flagged. This adds "CONTINUED" flag to footnotes that end in `...]*`.
Fixes #1236
=> Flag continued footnotes

src/guiguts/html_convert.py
If block markup (p, f, l, $, *, i, c, r), check there is a blank line before it, or an open blockquote or div, because block markup is permitted immediately inside blockquote without a blank line before it. One type of block markup cannot be nested inside another.
Fixes #1329
Testing notes: variations on the text in the linked issue should give error if any block type doesn't have a blank line before it, unless it's at the start of blockquote markup.
=> Warn if if no blank line before block in HTML-gen

src/guiguts/html_convert.py
Similar to existing behavior for `/#`, even if Multiline chapter headings is enabled, stop gathering h2 text if we see `/p`.
Fixes #1340
=> Make `/p` terminate `h2` markup

src/guiguts/maintext.py
If Home (or Cmd-Left) is pressed, go to start of line. If already at start of line, then go to first non-space on current line. If Shift is pressed then make selection or adjust start/end of existing selection to "home" position depending on where current insert position is.
Fixes #1160
=> Add advanced Home key behavior

src/guiguts/data/html/html_header.txt, src/guiguts/html_convert.py, tests/expected/htmlconvert1.txt, tests/expected/htmlconvert2.txt
For reasons linked from the issue, it's better to use the HTML blockquote tag. If a PPer really wants to use divs instead, a simple search/replace will suffice. This would not be true in reverse if the PPer wanted blockquotes and divs had been used, because the correct matching `/div` tags are harder to match.
A supplementary suggestion of introducing a new `/W` markup has not been implemented since it would mean added complexity in the code, the user interface and the documentation, with no visible difference for the user, particularly since the default blockquote CSS, and the existing "blockquot" div CSS leave the font size unchanged, contrary to the implication in the issue description.
Fixes #1294
1. Check results of HTML generation in `master` and this PR - differences in the HTML …
=> Use `blockquote` instead of `div class="blockquot"`

src/guiguts/application.py, src/guiguts/file.py, src/guiguts/maintext.py
When GG jumps to a location and displays it roughly in the center of the screen, e.g. through a Search or clicking on a Checker message (not with arrow keys or similar movements) the location (BEFORE jumping) is pushed on a stack. Go Back and Go Forward navigate through that stack, in a similar way to an Undo/Redo stack.
Fixes #916 (Buttons to be added to toolbar in #1342)
Note that as stated above, the location that is saved is the cursor position BEFORE the jump, not the location jumped to. This corresponds to "go back to where I was before I came here".
The stack size is limited to 100, which means you can go back 99 times (plus the location you first went back from), and from the final back step, you can go forward 99 times. If you want to reduce that for testing purposes, e.g. to 3 …
=> Add Go Back and Go Forward to Search menu

src/guiguts/application.py, src/guiguts/misc_tools.py
Add two new curly quote buttons, in a submenu. The first converts straight quotes that are inside HTML tags to obscure characters, just like ppsmq, but GG copes with tags that are split across line breaks, such as
```
<  div class
= "test"
>
```
Second button does the reverse, converting ALL
occurrences of contour/surface integral characters back to straight quotes.
This therefore provides at least the functionality of ppsmq, and can probably cope better with real-life occurrences of `<` or `>` in the text.
The reason for doing it this way rather than trying to make both Convert to Curly Quotes and Check Curly Quotes cope with HTML tags is that it would introduce too much complexity into the curly quotes code, potentially breaking it for the 99% of cases which are not HTML files.
Fixes …
=> Add support for HTML curly quote conversion

src/guiguts/tools/pphtml.py
Very similar to image checks, but does not open file to
inspect its type or width/height.
1. Checks files have valid extension (e.g. mp3, mid, mxl, etc)
2. Checks all files are referenced
3. Checks references point to actual files
4. Checks that `<audio>` elements have exactly the following text mandated by the music guidelines: "Audio content is not currently supported on your device." (allow missing period)
5. Lists the files in order of size
Example file in linked issue: #1128
=> Add music files checks to PPhtml

src/guiguts/application.py, src/guiguts/preferences.py, src/guiguts/widgets.py
1. Add right-click context menu to dialogs which should work anywhere in the dialog that doesn't already capture a right-click.
2. Context menu shows "Pin" or "Unpin", depending on current setting.
3. "Pinned" setting is stored per dialog in prefs file.
4. An entry in the View menu toggles the "pinned" setting for the dialog that has focus.
5. This entry can be assigned a shortcut in the usual way.
6. When pinned, a pin shows in the title bar of the dialog.
7. When pinned, dialog is subordinate to the main window in a way that means it remains in front, and moves up/down the window manager stack with the main window. If the main window is iconified/minimized, the pinned dialogs will be too.
8. When unpinned, a dialog continues to behave like a pinned dialog until it is closed and …
=> Add pinning to dialogs

README.md
Add `-q` argument and remove surplus backticks
Fixes #1376
=> Fix README Sphinx commands

src/guiguts/maintext.py
The default Tk Page Up/Down behavior goes up one more line than it goes down.
Manually implement page up/down to move the same
number of lines, as well as Shift+Page Up/Down to
select/extend selection by a page symmetrically.
Fixes #1373
=> Fix Page Up/Down to be symmetrical

src/guiguts/data/scannos/regex.json
This is regex number 15 in `regex.json`. Previously only the comma was captured and highlighted, so alpha sorting didn't appear to work, since every match was a comma. Changed to also capture the uppercase character after the comma, e.g. `, C` in `, Caesar`, so sorting is based on that character.
Note that, as previously, that uppercase `I` with a space after it is not matched by this regex, to avoid false positives from `Next, I followed...`
Fixes #1366
=> Improve ", <UPPERCASE>" regex to aid sorting

src/guiguts/maintext.py
If a line was longer than the right margin, then when it was centered, spaces were removed from the line, including between words (see linked issue).
Fixed by only removing leading spaces. If a line can't fit, it is shunted to the left margin as best it can be.
Fixes #1381
=> Fix "long line" centering bug

src/guiguts/html_tools.py
With Multiline on, if a row was spread across more than one line, it left an copy of an original line at the top of the table
Fixes #1380
=> Fix Autotable bug

src/guiguts/search.py
The combination of word boundary with a non-greedy match caused the replacement to be incorrect.
Example:
S: `\b.+?\b`
R: `X`
This should find words, i.e. groups of characters delimited by word boundaries, and replace it with a single `X`. In fact it replaced every character in the word with `X`.
This is because we can't use Tcl regex replacement since it is very limited, so we have to get the match into a python string, e.g. `word`. We now execute the replacement on that string. This means it does not have context, so word boundaries and look-ahead/behind at the start and end of the string don't work. We therefore removed them from the search string used on the Python string.
However, this means that the search term is now `.+?`, which matches just the `w` in `word`, which it replaces …
=> Fix word boundary regex bug

src/guiguts/maintext.py
On Macs it's the Command-Left key
Fixes #1385
=> Make "Home" key scroll left if needed

src/guiguts/widgets.py
Remove calls to `update()` from the recursive calls to set the cursor shape. So instead of 100-200 calls to update, there should now be 2.
This still works acceptably on Windows & Linux (WSL), but needs testing on Macs
Previous suggestion, to not change the cursor recursively on the widgets, stop the cursor being changed on Windows, at least.
=> Attempt to speed up "Busy" on Macs

src/guiguts/application.py, src/guiguts/content_providing.py, src/guiguts/file.py, src/guiguts/maintext.py, src/guiguts/preferences.py, src/guiguts/word_frequency.py
1. Update list of character suites and which characters they contain from the DP website (GG1 is out of date)
2. File-->Content Providing-->Highlight WF Chars not in Selected Suites turns on/off highlighting in the Word Frequency dialog when in Character Count mode.
3. If a character is not in a currently selected character suite, or not in any character suite, it is highlighted.
4. If the character suite is known, its name is printed, also highlighted, next to the character.
5. If the character is in several suites, they are all listed.
6. If the character is in no suites, that is reported.
7. File-->Content Providing-->Manage Character Suites allows the user to enable or disable any of the DP character suites.
8. The list of char suites is stored in the project bin/json file.
=> Add Character Suite support

src/guiguts/tools/pphtml.py
Add to the miscellaneous special checks near the end. Should catch `_this_`, `_multi word on one line phrase_`, `_broken`, `missing_`, `P_art_`, but not `mid_word`. It's detecting when there's an underscore at the start and/or end of the word, but permits mid-word underscores.
Fixes #1375
=> Report unconverted italics in PPhtml

src/guiguts/tools/bookloupe.py
`"This".` is now acceptable, and won't be reported by bookloupe, along with `"This",`, `"This."`, or `"This,"`, but `"This"` will still be reported.
Fixes #1382
=> Allow punctuation after quotes in bookloupe

src/guiguts/content_providing.py
There are still some old Latin1 files lying around. Read them, rather then throwing an exception.
=> Read Latin1 prep text files correctly

src/guiguts/application.py, src/guiguts/misc_tools.py, src/guiguts/search.py
It's a clone of the GG1 feature. Starting from the top of the
file, it replaces the first `[::]` with `1`, then next with `2`, etc.
Fixes [#1370](https://github.com/DistributedProofreaders/guiguts-py/issues/1370)
Increments & returns the value referenced by the key.
E.g.
`\Ccinc("X")\E` will increment the value stored in X, and
will be replaced by that value. If "X" doesn't exist, it is
assumed to be zero, so the first call will return "1".
Using this as a replacement expression is equivalent to
the `[::]` incremental feature, but more flexible, since it
can easily be made to start at any value, using
`\Ccset("X", 27)\E` as a replacement before all the other
replacements.
=> Sequential Counter

src/guiguts/application.py
For some reason, I added an "else" when implementing the toolbar/message bar, and broke the auto theme
changing.
=> Fix automatic theme changing

src/guiguts/application.py, src/guiguts/html_convert.py, src/guiguts/preferences.py, tests/actual/htmlconvert1.txt
If checkbox is on, detect two blank lines followed by a single line of text then a blank line, and mark it up as an `h3` heading.
Multi-line text following 2 blank lines is not treated as h3, but will just receive `p` markup.
Also, if the single line is an illo, footnote, etc., or block markup, it will not be converted to `h3`
Fixes #1367
=> Optionally add `h3` markup during autogen

src/guiguts/maintext.py
Previous Mac edit broke it when user had NumLock pressed. Make Mac edit Mac-specific.
Fixes [comment](https://github.com/DistributedProofreaders/guiguts-py/pull/1411#issuecomment-3288675372) in #1411
=> Fix copy-dragging

src/guiguts/maintext.py
Wrap user's regex in non-capturing parentheses so low priority elements like `|` don't end up splitting the regex into two parts with the word-begin on the first part and the word-end on the second part.
=> Fix whole word bug with regex

src/guiguts/application.py, src/guiguts/illo_sn_fixup.py, src/guiguts/preferences.py
The "Preserve Illo's Page Number" checkbox is only supposed to apply to Illo Fixup, not Sidenote Fixup, and only appears in Illo Fixup. However the code was applying it to sidenotes too.
Test file in linked issue.
Fixes #1457 (second part only)
=> Fix "Preserve Illo's Page Number" bug in SN Fixup

src/guiguts/misc_dialogs.py
macOS needs a VS15 added to the white square used to indicate an outline in the color prefs tab.
=> Add VS15 to white square in color prefs

src/guiguts/application.py
An error in the way the old menus were removed and the new ones created when Custom Menu was used gave an exception. Fixed with explicit destroy call to submenu.
Fixes #1463
Testing notes - Go to Custom Menu--> Customize Menu, change label or command of first menu option, and click Update.
=> Fix Customize Menu exception

src/guiguts/footnotes.py
If user tries to reindex when there are unpaired footnote anchors, it generated an exception. Instead output an error message, so user can fix the problem, either by pairing up the anchor, or editing it to `{{123}}` so it is not recognized as an anchor.
Test file: agricola-test-busy after changing one of the `{{nnn}}` back to `[nnn]`, then using Reindex.
=> Fix exception from unpaired footnote anchors

src/guiguts/footnotes.py
An example would be a date in square brackets, e.g. `[1928]` which the FN code would interpret as an anchor. If PPer precedes the open bracket with backslash, FN fixup will now ignore it.
Fixes #1485
=> Allow escaping of FN anchors with backslash
